/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ourits.jobcosting.ui;

import com.ourits.jobcosting.helpers.InvokerHelper;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JSeparator;
import javax.swing.JMenuItem;
import javax.swing.SwingConstants;
import javax.swing.JMenu;

/**
 *
 * @author Other guest
 */
public class HomeSreen extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form NewJFrame
	 */
	public HomeSreen() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		buttonProjectEntry = new javax.swing.JButton();
		labelProjectEntry = new javax.swing.JLabel();
		buttonSubProjectEntry = new javax.swing.JButton();
		labelSubProjectEntry = new javax.swing.JLabel();
		labelTaskEntry = new javax.swing.JLabel();
		buttonTaskEntry = new javax.swing.JButton();
		buttonExpensesEntry = new javax.swing.JButton();
		labelExpensesEntry = new javax.swing.JLabel();
		buttonBackup = new javax.swing.JButton();
		label = new javax.swing.JLabel();
		seperatorLogAndButtons = new javax.swing.JSeparator();
		labelCompanyCopyrights = new javax.swing.JLabel();
		seperatorLogoAndDashboard = new javax.swing.JSeparator();
		labelDashboard = new javax.swing.JLabel();
		labelAlerts = new javax.swing.JLabel();
		labelmilestones = new javax.swing.JLabel();
		labelReports = new javax.swing.JLabel();
		companyLogo = new javax.swing.JLabel();
		labelAccountSettings = new javax.swing.JLabel();
		labelCompanyName = new javax.swing.JLabel();
		companyLogoPanel = new javax.swing.JPanel();
		labelCompanyLogo = new javax.swing.JLabel();
		menubar = new javax.swing.JMenuBar();
		menuItemFile = new javax.swing.JMenu();
		menuItemEdit = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setResizable(false);
		buttonProjectEntry
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1474589767_Portfolio.png"))); // NOI18N
		buttonProjectEntry.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonProjectEntryActionPerformed(evt);
			}
		});

		labelProjectEntry.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
		labelProjectEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelProjectEntry.setLabelFor(buttonProjectEntry);
		labelProjectEntry.setText("Project Entry");
		labelProjectEntry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		buttonSubProjectEntry
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1474591217_Draft.png"))); // NOI18N
		buttonSubProjectEntry.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonSubProjectEntryActionPerformed(evt);
			}
		});

		labelSubProjectEntry.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
		labelSubProjectEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelSubProjectEntry.setLabelFor(buttonProjectEntry);
		labelSubProjectEntry.setText("Sub Project Entry");
		labelSubProjectEntry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		labelTaskEntry.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
		labelTaskEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelTaskEntry.setLabelFor(buttonProjectEntry);
		labelTaskEntry.setText("Task Entry");
		labelTaskEntry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		buttonTaskEntry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1474591225_Todo.png"))); // NOI18N
		buttonTaskEntry.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonTaskEntryActionPerformed(evt);
			}
		});

		buttonExpensesEntry.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/images/1474591405_Project Plan - Gant Chart.png"))); // NOI18N
		buttonExpensesEntry.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonExpensesEntryActionPerformed(evt);
			}
		});

		labelExpensesEntry.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
		labelExpensesEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelExpensesEntry.setLabelFor(buttonProjectEntry);
		labelExpensesEntry.setText("Expenses Entry");
		labelExpensesEntry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		buttonBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1474591768_backup.png"))); // NOI18N

		label.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
		label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		label.setLabelFor(buttonProjectEntry);
		label.setText("Backup");
		label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		labelCompanyCopyrights.setText("(c) Intuitive Technologies & Solutions | All rights reserved");

		seperatorLogoAndDashboard.setOrientation(javax.swing.SwingConstants.VERTICAL);

		labelDashboard.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
		labelDashboard.setForeground(new java.awt.Color(102, 102, 255));
		labelDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1474593395_Bar_Graph80x90.png"))); // NOI18N
		labelDashboard.setText("Dashboard");

		labelAlerts.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
		labelAlerts.setForeground(new java.awt.Color(102, 102, 255));
		labelAlerts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon - alert.png"))); // NOI18N
		labelAlerts.setText("Alerts");

		labelmilestones.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
		labelmilestones.setForeground(new java.awt.Color(102, 102, 255));
		labelmilestones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1474594325_Milestone100x100.png"))); // NOI18N
		labelmilestones.setText("Milestones");

		labelReports.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
		labelReports.setForeground(new java.awt.Color(102, 102, 255));
		labelReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1474594919_vector_65_1480x90.png"))); // NOI18N
		labelReports.setText("Reports");

		labelAccountSettings.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
		labelAccountSettings.setForeground(new java.awt.Color(0, 51, 153));
		labelAccountSettings.setText("Account settings");

		labelCompanyName.setFont(new java.awt.Font("Arial Narrow", 2, 18)); // NOI18N
		labelCompanyName.setText("INTUITIVE TECHNOLOGIES & SOLUTIONS");
		labelCompanyName.setToolTipText("");

		labelCompanyLogo.setIcon(new javax.swing.ImageIcon(
				getClass().getResource("/images/00106-3D-company-logos-design-free-logo-online-02.png"))); // NOI18N

		javax.swing.GroupLayout gl_companyLogoPanel = new javax.swing.GroupLayout(companyLogoPanel);
		gl_companyLogoPanel.setHorizontalGroup(
			gl_companyLogoPanel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_companyLogoPanel.createSequentialGroup()
					.addContainerGap()
					.addComponent(labelCompanyLogo, GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
					.addContainerGap())
		);
		gl_companyLogoPanel.setVerticalGroup(
			gl_companyLogoPanel.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, gl_companyLogoPanel.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(labelCompanyLogo)
					.addContainerGap())
		);
		companyLogoPanel.setLayout(gl_companyLogoPanel);

		menuItemFile.setText("File");
		menubar.add(menuItemFile);

		menuItemEdit.setText("Edit");
		menubar.add(menuItemEdit);

		setJMenuBar(menubar);
		
		Help = new JMenu("Help");
		menubar.add(Help);
		
		JSeparator seperatorBottom = new JSeparator();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(seperatorBottom, GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
									.addComponent(companyLogoPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(companyLogo))
								.addGroup(layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addComponent(labelAccountSettings)
										.addComponent(labelCompanyName, GroupLayout.PREFERRED_SIZE, 319, GroupLayout.PREFERRED_SIZE))
									.addGap(0, 145, Short.MAX_VALUE)))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(seperatorLogoAndDashboard, GroupLayout.PREFERRED_SIZE, 2, GroupLayout.PREFERRED_SIZE)
							.addGap(12)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
									.addComponent(labelDashboard, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
									.addGap(18)
									.addComponent(labelAlerts, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
									.addComponent(labelmilestones)
									.addGap(29)
									.addComponent(labelReports, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))))
						.addGroup(layout.createSequentialGroup()
							.addGap(0, 570, Short.MAX_VALUE)
							.addComponent(labelCompanyCopyrights))
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(buttonProjectEntry, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(labelProjectEntry, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE))
									.addGap(18)
									.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(buttonSubProjectEntry, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(labelSubProjectEntry, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE))
									.addGap(18)
									.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(labelTaskEntry, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(buttonTaskEntry))
									.addGap(18)
									.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(buttonExpensesEntry, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(labelExpensesEntry, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE))
									.addGap(18)
									.addGroup(layout.createParallelGroup(Alignment.TRAILING)
										.addComponent(buttonBackup, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
										.addComponent(label, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)))
								.addComponent(seperatorLogAndButtons, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 890, GroupLayout.PREFERRED_SIZE))
							.addGap(0, 11, Short.MAX_VALUE)))
					.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGap(186)
							.addComponent(companyLogo)
							.addPreferredGap(ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
							.addComponent(labelCompanyName)
							.addGap(18)
							.addComponent(labelAccountSettings)
							.addGap(36))
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
									.addGap(46)
									.addGroup(layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(labelDashboard)
										.addComponent(labelAlerts))
									.addGap(60)
									.addGroup(layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(labelmilestones)
										.addComponent(labelReports)))
								.addGroup(layout.createSequentialGroup()
									.addContainerGap()
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addComponent(companyLogoPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(seperatorLogoAndDashboard, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE))))
							.addPreferredGap(ComponentPlacement.RELATED, 13, Short.MAX_VALUE)))
					.addComponent(seperatorLogAndButtons, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
					.addGap(13)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
							.addGroup(layout.createSequentialGroup()
								.addComponent(buttonTaskEntry, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
								.addGap(18)
								.addComponent(labelTaskEntry))
							.addGroup(layout.createSequentialGroup()
								.addComponent(buttonSubProjectEntry)
								.addGap(18)
								.addComponent(labelSubProjectEntry))
							.addGroup(layout.createSequentialGroup()
								.addComponent(buttonProjectEntry)
								.addGap(18)
								.addComponent(labelProjectEntry)))
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
								.addComponent(buttonBackup, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(buttonExpensesEntry))
							.addGap(18)
							.addComponent(labelExpensesEntry)))
					.addGap(18)
					.addComponent(seperatorBottom, GroupLayout.PREFERRED_SIZE, 2, GroupLayout.PREFERRED_SIZE)
					.addGap(12)
					.addComponent(labelCompanyCopyrights)
					.addContainerGap())
				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
					.addContainerGap(510, Short.MAX_VALUE)
					.addComponent(label)
					.addGap(56))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void buttonProjectEntryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonProjectEntryActionPerformed
		InvokerHelper invokerHelper = new InvokerHelper();
		invokerHelper.doInvoke(new ProjectEntry());
	}// GEN-LAST:event_buttonProjectEntryActionPerformed

	private void buttonSubProjectEntryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSubProjectEntryActionPerformed
		InvokerHelper invokerHelper = new InvokerHelper();
		invokerHelper.doInvoke(new SubProjectEntry());
	}// GEN-LAST:event_buttonSubProjectEntryActionPerformed

	private void buttonTaskEntryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonTaskEntryActionPerformed
		InvokerHelper invokerHelper = new InvokerHelper();
		invokerHelper.doInvoke(new TaskEntry());
	}// GEN-LAST:event_buttonTaskEntryActionPerformed

	private void buttonExpensesEntryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonExpensesEntryActionPerformed
		InvokerHelper invokerHelper = new InvokerHelper();
		invokerHelper.doInvoke(new ProjectExpensesEntry());
	}// GEN-LAST:event_buttonExpensesEntryActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HomeSreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HomeSreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HomeSreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HomeSreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HomeSreen().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonBackup;
	private javax.swing.JButton buttonExpensesEntry;
	private javax.swing.JButton buttonProjectEntry;
	private javax.swing.JButton buttonSubProjectEntry;
	private javax.swing.JButton buttonTaskEntry;
	private javax.swing.JLabel labelProjectEntry;
	private javax.swing.JLabel labelCompanyCopyrights;
	private javax.swing.JLabel labelDashboard;
	private javax.swing.JLabel labelAlerts;
	private javax.swing.JLabel labelmilestones;
	private javax.swing.JLabel labelReports;
	private javax.swing.JLabel labelSubProjectEntry;
	private javax.swing.JLabel labelTaskEntry;
	private javax.swing.JLabel labelExpensesEntry;
	private javax.swing.JLabel label;
	private javax.swing.JLabel companyLogo;
	private javax.swing.JPanel companyLogoPanel;
	private javax.swing.JLabel labelAccountSettings;
	private javax.swing.JLabel labelCompanyLogo;
	private javax.swing.JLabel labelCompanyName;
	private javax.swing.JMenu menuItemEdit;
	private javax.swing.JMenu menuItemFile;
	private javax.swing.JMenuBar menubar;
	private javax.swing.JSeparator seperatorLogAndButtons;
	private javax.swing.JSeparator seperatorLogoAndDashboard;
	private JMenu Help;
}
