/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ourits.jobcosting.ui;

import java.awt.Color;
import java.awt.SystemColor;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import javax.swing.Action;

import com.ourits.jobcosting.entities.ProjectIdentifier;
import com.ourits.jobcosting.entities.ProjectIdentifierPK;
import com.ourits.jobcosting.persistencehelpers.BasePersistenceHelpers;

import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.sql.Date;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JTabbedPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Other guest
 */
public class ProjectEntry extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form NewJFrame
	 */
	public ProjectEntry() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane5 = new javax.swing.JTabbedPane();
		jCalendar1 = new com.toedter.calendar.JCalendar();
		labelCompanyCopyrights = new javax.swing.JLabel();
		filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 150),
				new java.awt.Dimension(32767, 150));
		jLabel6 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		projectEntry = new javax.swing.JTabbedPane();
		projectEntry.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
		panelNewEntry = new javax.swing.JPanel();
		labelProjectCode = new javax.swing.JLabel();
		textFieldProjectCode = new javax.swing.JTextField();
		textFieldProjectCode.setColumns(10);
		labelProjectDesc = new javax.swing.JLabel();
		projectDescArea = new javax.swing.JScrollPane();
		textAreaProjectDescription = new javax.swing.JTextArea();
		labelStartDate = new javax.swing.JLabel();
		dateChooserStartDate = new com.toedter.calendar.JDateChooser();
		labelEndDate = new javax.swing.JLabel();
		dateChooserEndDate = new com.toedter.calendar.JDateChooser();
		labelBudgetAmt = new javax.swing.JLabel();
		textFieldBudgetAmount = new javax.swing.JTextField();
		dropdownCurrency = new javax.swing.JComboBox<>();
		labelProjectName = new javax.swing.JLabel();
		textFieldProjectName = new javax.swing.JTextField();
		jSeparator1 = new javax.swing.JSeparator();
		labelRevisedStartDate = new javax.swing.JLabel();
		labelRevisedStartDate.setEnabled(false);
		dateChooserRevisedStartDate = new com.toedter.calendar.JDateChooser();
		dateChooserRevisedStartDate.getCalendarButton().setBackground(SystemColor.activeCaptionBorder);
		dateChooserRevisedStartDate.getCalendarButton().setEnabled(false);
		labelRevisedEndDate = new javax.swing.JLabel();
		labelRevisedEndDate.setEnabled(false);
		datechooserRevisedEndDate = new com.toedter.calendar.JDateChooser();
		datechooserRevisedEndDate.setBackground(Color.LIGHT_GRAY);
		datechooserRevisedEndDate.getCalendarButton().setEnabled(false);
		labelRevisedBudgetAmount = new javax.swing.JLabel();
		labelRevisedBudgetAmount.setEnabled(false);
		textFieldRevisedBudgetAmt = new javax.swing.JTextField();
		textFieldRevisedBudgetAmt.setEnabled(false);
		textFieldRevisedBudgetAmt.setEditable(false);
		dropdownRevisedCurrency = new javax.swing.JComboBox<>();
		dropdownRevisedCurrency.setEnabled(false);
		buttonAddEntry = new javax.swing.JButton();
		buttonAddEntry.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				performProjectAddEntry();
			}

			private void performProjectAddEntry() {
				final BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				final ProjectIdentifier projectIdentifier = buildProjectIdentifier();
				basePersistenceHelpers.createProjectIdentifier(projectIdentifier);
			}

			private ProjectIdentifier buildProjectIdentifier() {
				ProjectIdentifier projectIdentifier = new ProjectIdentifier();
				ProjectIdentifierPK id = new ProjectIdentifierPK();
				id.setProjectId(textFieldProjectCode.getText());
				id.setProjectName(textFieldProjectName.getText());
				projectIdentifier.setId(id);
				projectIdentifier.setProjectAmountCurrency(String.valueOf(dropdownCurrency.getSelectedItem()));
				projectIdentifier.setProjectBudgetAmt(new BigDecimal(textFieldBudgetAmount.getText()));
				projectIdentifier.setProjectDesc(textAreaProjectDescription.getText());
				projectIdentifier.setProjectEndDate(dateChooserEndDate.getDate());
				projectIdentifier.setProjectStrtDate(dateChooserStartDate.getDate());
				return projectIdentifier;
			}
		});
		buttonAddEntry.setAction(action);
		buttonCancel = new javax.swing.JButton();
		buttonCancel.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});
		buttonReset = new javax.swing.JButton();
		buttonReset.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				textFieldProjectCode.setText(null);
				textFieldProjectName.setText(null);
				textAreaProjectDescription.setText(null);
				textFieldBudgetAmount.setText(null);
				dateChooserEndDate.setDate(null);
				dateChooserStartDate.setDate(null);
				dropdownCurrency.setSelectedIndex(0);
			}
		});
		jPanel2 = new javax.swing.JPanel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jLabel16 = new javax.swing.JLabel();
		jDateChooser5 = new com.toedter.calendar.JDateChooser();
		jLabel17 = new javax.swing.JLabel();
		jDateChooser6 = new com.toedter.calendar.JDateChooser();
		jLabel18 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField();
		jComboBox3 = new javax.swing.JComboBox<>();
		jLabel19 = new javax.swing.JLabel();
		jDateChooser7 = new com.toedter.calendar.JDateChooser();
		jLabel20 = new javax.swing.JLabel();
		jDateChooser8 = new com.toedter.calendar.JDateChooser();
		jLabel21 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jComboBox4 = new javax.swing.JComboBox<>();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jComboBox5 = new javax.swing.JComboBox<>();
		jComboBox6 = new javax.swing.JComboBox<>();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jSeparator2 = new javax.swing.JSeparator();
		jPanel3 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jLabel25 = new javax.swing.JLabel();
		jLabel26 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jLabel27 = new javax.swing.JLabel();
		jDateChooser9 = new com.toedter.calendar.JDateChooser();
		jLabel28 = new javax.swing.JLabel();
		jDateChooser10 = new com.toedter.calendar.JDateChooser();
		jLabel29 = new javax.swing.JLabel();
		jTextField9 = new javax.swing.JTextField();
		jComboBox9 = new javax.swing.JComboBox<>();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton13 = new javax.swing.JButton();
		jButton15 = new javax.swing.JButton();
		jComboBox13 = new javax.swing.JComboBox<>();
		jLabel30 = new javax.swing.JLabel();
		jComboBox14 = new javax.swing.JComboBox<>();
		jButton16 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		labelCompanyCopyrights.setText("(c) Intuitive Technologies & Solutions | All rights reserved");

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel1.setText("Project Entry Details ");

		projectEntry.setBorder(
				new MatteBorder(1, 1, 1, 1, (Color) new Color(0, 0, 0)));

		panelNewEntry.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		labelProjectCode.setText("Project Code ");

		textFieldProjectCode.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		labelProjectDesc.setText("Description");

		textAreaProjectDescription.setColumns(20);
		textAreaProjectDescription.setRows(10);
		projectDescArea.setViewportView(textAreaProjectDescription);

		labelStartDate.setText("Start Date");

		labelEndDate.setText("End Date");

		labelBudgetAmt.setText("Budget Amount");

		dropdownCurrency
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		labelProjectName.setText("Project Name ");

		textFieldProjectName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});

		labelRevisedStartDate.setText("Revised Start Date");

		labelRevisedEndDate.setText("Revised End Date");

		labelRevisedBudgetAmount.setText("Revised Budget Amount");

		dropdownRevisedCurrency
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		buttonAddEntry.setText("Add Entry");

		buttonCancel.setText("Cancel");

		buttonReset.setText("Reset");

		javax.swing.GroupLayout gl_panelNewEntry = new javax.swing.GroupLayout(panelNewEntry);
		panelNewEntry.setLayout(gl_panelNewEntry);
		gl_panelNewEntry.setHorizontalGroup(gl_panelNewEntry
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_panelNewEntry.createSequentialGroup().addContainerGap().addGroup(gl_panelNewEntry
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSeparator1)
						.addGroup(gl_panelNewEntry.createSequentialGroup()
								.addGroup(
										gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(labelProjectCode).addComponent(labelProjectDesc)
												.addComponent(labelStartDate).addComponent(labelEndDate)
												.addComponent(labelBudgetAmt).addComponent(labelProjectName))
								.addGap(18, 18, 18)
								.addGroup(gl_panelNewEntry
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(textFieldProjectCode)
										.addComponent(projectDescArea, javax.swing.GroupLayout.DEFAULT_SIZE, 263,
												Short.MAX_VALUE)
										.addComponent(dateChooserStartDate, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(dateChooserEndDate, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_panelNewEntry
												.createSequentialGroup().addComponent(textFieldBudgetAmount)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(dropdownCurrency, javax.swing.GroupLayout.PREFERRED_SIZE,
														82, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(textFieldProjectName)))
						.addGroup(gl_panelNewEntry.createSequentialGroup()
								.addGroup(
										gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(labelRevisedStartDate)
												.addComponent(labelRevisedEndDate)
												.addComponent(labelRevisedBudgetAmount))
								.addGap(18, 18, 18)
								.addGroup(gl_panelNewEntry
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_panelNewEntry
												.createSequentialGroup()
												.addComponent(textFieldRevisedBudgetAmt,
														javax.swing.GroupLayout.PREFERRED_SIZE, 129,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(dropdownRevisedCurrency,
														javax.swing.GroupLayout.PREFERRED_SIZE, 79,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(datechooserRevisedEndDate, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(dateChooserRevisedStartDate,
												javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								gl_panelNewEntry.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
										.addComponent(buttonAddEntry)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(buttonReset).addGap(10, 10, 10).addComponent(buttonCancel)))
						.addContainerGap()));
		gl_panelNewEntry.setVerticalGroup(gl_panelNewEntry
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_panelNewEntry.createSequentialGroup().addGap(7, 7, 7)
						.addGroup(gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(labelProjectName).addComponent(textFieldProjectName,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(labelProjectCode).addComponent(textFieldProjectCode,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(labelProjectDesc).addComponent(projectDescArea,
										javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(26, 26, 26)
						.addGroup(gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(dateChooserStartDate, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(labelStartDate))
						.addGap(18, 18, 18)
						.addGroup(gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(dateChooserEndDate, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(labelEndDate))
						.addGap(18, 18, 18)
						.addGroup(gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(gl_panelNewEntry
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(textFieldBudgetAmount, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(dropdownCurrency, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(labelBudgetAmt))
						.addGap(18, 18, 18)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(32, 32, 32)
						.addGroup(gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(dateChooserRevisedStartDate, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(labelRevisedStartDate))
						.addGap(18, 18, 18)
						.addGroup(gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(datechooserRevisedEndDate, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(labelRevisedEndDate))
						.addGap(18, 18, 18)
						.addGroup(gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(gl_panelNewEntry
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(textFieldRevisedBudgetAmt, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(dropdownRevisedCurrency, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(labelRevisedBudgetAmount))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
						.addGroup(gl_panelNewEntry.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(buttonAddEntry).addComponent(buttonCancel).addComponent(buttonReset))
						.addContainerGap()));

		projectEntry.addTab("New Entry", panelNewEntry);

		jLabel13.setText("Project Name ");

		jLabel14.setText("Project Code ");

		jLabel15.setText("Description");

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		jLabel16.setText("Start Date");

		jLabel17.setText("End Date");

		jLabel18.setText("Budget Amount");

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		jLabel19.setText("Revised Start Date");

		jLabel20.setText("Revised End Date");

		jLabel21.setText("Revised Budget Amount");

		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		jButton4.setText("Update Entry");

		jButton5.setText("Reset");

		jButton6.setText("Cancel");

		jComboBox5.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jComboBox6.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jButton7.setText("jButton7");

		jButton8.setText("jButton7");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel14).addComponent(jLabel13))
								.addGap(27, 27, 27)
								.addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jComboBox6, 0, 209, Short.MAX_VALUE).addComponent(jComboBox5, 0,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE,
												41, Short.MAX_VALUE)
										.addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
												Short.MAX_VALUE))
								.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout.createSequentialGroup().addComponent(jLabel15)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46,
												Short.MAX_VALUE)
										.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap())
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel16).addComponent(jLabel17).addComponent(jLabel18))
										.addGap(18, 18, 18)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jDateChooser6, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														jPanel2Layout.createSequentialGroup().addComponent(jTextField7)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jComboBox3,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 82,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(jDateChooser5, javax.swing.GroupLayout.DEFAULT_SIZE, 263,
														Short.MAX_VALUE)))
								.addGroup(jPanel2Layout
										.createSequentialGroup().addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel19).addComponent(jLabel20).addComponent(jLabel21))
										.addGap(18, 18, 18)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														jPanel2Layout.createSequentialGroup()
																.addComponent(jTextField8,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 129,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jComboBox4,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 79,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(jDateChooser8, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jDateChooser7, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel2Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addComponent(jButton4)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jButton5).addGap(10, 10, 10).addComponent(jButton6)))
								.addContainerGap()))
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jSeparator2)
								.addContainerGap())));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jButton7)
						.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton8).addComponent(jLabel13))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel14))))
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel15))
						.addContainerGap(354, Short.MAX_VALUE))
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(187, 187, 187)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel16))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jDateChooser6, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel17))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jLabel18))
								.addGap(52, 52, 52)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jDateChooser7, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel19))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jDateChooser8, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel20))
								.addGap(18, 18, 18)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jLabel21))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47,
										Short.MAX_VALUE)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton4).addComponent(jButton6).addComponent(jButton5))
								.addGap(10, 10, 10)))
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(323, 323, 323)
								.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(200, Short.MAX_VALUE))));

		projectEntry.addTab("Update Entry", jPanel2);

		jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jLabel25.setText("Project Code ");

		jLabel26.setText("Description");

		jTextArea3.setColumns(20);
		jTextArea3.setRows(5);
		jScrollPane3.setViewportView(jTextArea3);

		jLabel27.setText("Start Date");

		jLabel28.setText("End Date");

		jLabel29.setText("Budget Amount");

		jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		jButton11.setText("Close Entry");

		jButton12.setText("Reset");

		jButton13.setText("Cancel");

		jButton15.setText("jButton7");

		jComboBox13.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox13ActionPerformed(evt);
			}
		});

		jLabel30.setText("Project Name ");

		jComboBox14.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jButton16.setText("jButton7");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout
						.createSequentialGroup()
						.addContainerGap().addGroup(jPanel4Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout
										.createSequentialGroup().addComponent(jLabel30).addGap(31, 31, 31)
										.addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 209,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel4Layout.createSequentialGroup().addComponent(jLabel26)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel25)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 209,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap())
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel27).addComponent(jLabel28).addComponent(jLabel29))
												.addGap(18, 18, 18)
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jDateChooser10,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout.createSequentialGroup()
																		.addComponent(jTextField9)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jComboBox9,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				82,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(jDateChooser9,
																javax.swing.GroupLayout.DEFAULT_SIZE, 263,
																Short.MAX_VALUE)))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout
												.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addComponent(jButton11)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jButton12).addGap(10, 10, 10).addComponent(jButton13)))
										.addContainerGap())));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton15).addComponent(jLabel30).addComponent(jComboBox13,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel25).addComponent(jButton16).addComponent(jComboBox14,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel26))
						.addContainerGap(347, Short.MAX_VALUE))
				.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup().addGap(187, 187, 187)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jDateChooser9, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel27))
								.addGap(18, 18, 18)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jDateChooser10, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel28))
								.addGap(18, 18, 18)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jLabel29))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197,
										Short.MAX_VALUE)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton11).addComponent(jButton13).addComponent(jButton12))
								.addGap(10, 10, 10))));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addGap(0, 0, Short.MAX_VALUE)
					.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 396, GroupLayout.PREFERRED_SIZE))
		);
		jPanel3Layout.setVerticalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addGap(0, 0, Short.MAX_VALUE)
					.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		);
		jPanel3.setLayout(jPanel3Layout);

		projectEntry.addTab("Close Entry", jPanel3);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addGap(12, 12, 12).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addComponent(labelCompanyCopyrights))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(projectEntry)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel6).addGap(0, 0, 0).addComponent(filler1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap())
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGap(152, 152, 152)
														.addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(layout.createSequentialGroup().addGap(180, 180, 180)
														.addComponent(jLabel6)))
												.addGap(23, 23, 23))
								.addGroup(layout.createSequentialGroup().addGap(10, 10, 10).addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(projectEntry)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
						.addComponent(labelCompanyCopyrights).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField3ActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox13ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox13ActionPerformed

	/**
	 * jComboBox
	 * 
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ProjectEntry().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.Box.Filler filler1;
	private javax.swing.JButton buttonAddEntry;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton buttonCancel;
	private javax.swing.JButton buttonReset;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private com.toedter.calendar.JCalendar jCalendar1;
	private javax.swing.JComboBox<String> dropdownCurrency;
	private javax.swing.JComboBox<String> jComboBox13;
	private javax.swing.JComboBox<String> jComboBox14;
	private javax.swing.JComboBox<String> dropdownRevisedCurrency;
	private javax.swing.JComboBox<String> jComboBox3;
	private javax.swing.JComboBox<String> jComboBox4;
	private javax.swing.JComboBox<String> jComboBox5;
	private javax.swing.JComboBox<String> jComboBox6;
	private javax.swing.JComboBox<String> jComboBox9;
	private com.toedter.calendar.JDateChooser dateChooserStartDate;
	private com.toedter.calendar.JDateChooser jDateChooser10;
	private com.toedter.calendar.JDateChooser dateChooserEndDate;
	private com.toedter.calendar.JDateChooser dateChooserRevisedStartDate;
	private com.toedter.calendar.JDateChooser datechooserRevisedEndDate;
	private com.toedter.calendar.JDateChooser jDateChooser5;
	private com.toedter.calendar.JDateChooser jDateChooser6;
	private com.toedter.calendar.JDateChooser jDateChooser7;
	private com.toedter.calendar.JDateChooser jDateChooser8;
	private com.toedter.calendar.JDateChooser jDateChooser9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel labelCompanyCopyrights;
	private javax.swing.JLabel labelRevisedEndDate;
	private javax.swing.JLabel labelRevisedBudgetAmount;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel labelProjectCode;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel27;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel labelProjectDesc;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel labelStartDate;
	private javax.swing.JLabel labelEndDate;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel labelBudgetAmt;
	private javax.swing.JLabel labelProjectName;
	private javax.swing.JLabel labelRevisedStartDate;
	private javax.swing.JPanel panelNewEntry;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane projectDescArea;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JTabbedPane jTabbedPane5;
	private javax.swing.JTextArea textAreaProjectDescription;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextField textFieldProjectCode;
	private javax.swing.JTextField textFieldBudgetAmount;
	private javax.swing.JTextField textFieldProjectName;
	private javax.swing.JTextField textFieldRevisedBudgetAmt;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	private javax.swing.JTabbedPane projectEntry;
	private final Action action = new SwingAction();

	// End of variables declaration//GEN-END:variables
	private class SwingAction extends AbstractAction {
		public SwingAction() {
			putValue(NAME, "SwingAction");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}

		public void actionPerformed(ActionEvent e) {
		}
	}
}
