/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ourits.jobcosting.ui;

import java.awt.Color;
import java.awt.SystemColor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import java.util.List;

import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JSeparator;
import javax.swing.JTabbedPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.MatteBorder;

import com.ourits.jobcosting.entities.ProjectIdentifier;
import com.ourits.jobcosting.entities.ProjectIdentifierPK;
import com.ourits.jobcosting.persistencehelpers.BasePersistenceHelpers;
import javax.swing.JLabel;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import com.toedter.calendar.JDateChooser;
import javax.swing.JTextArea;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.ComponentOrientation;
import javax.swing.border.LineBorder;

/**
 *
 * @author Other guest
 */
public class ProjectEntry extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form NewJFrame
	 */
	public ProjectEntry() {
		getContentPane().setFocusTraversalKeysEnabled(false);
		getContentPane().setFocusTraversalPolicyProvider(true);
		getContentPane().setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
		getContentPane().addComponentListener(new ComponentAdapter() {
			@Override
			public void componentResized(ComponentEvent e) {
			}
		});
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane5 = new javax.swing.JTabbedPane();
		jCalendar1 = new com.toedter.calendar.JCalendar();
		labelCompanyCopyrights = new javax.swing.JLabel();
		filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 150),
				new java.awt.Dimension(32767, 150));
		jLabel6 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		projectEntry = new javax.swing.JTabbedPane();
		projectEntry.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
		panelNewEntry = new javax.swing.JPanel();
		panelNewEntry.setEnabled(false);
		panelNewEntry.setAutoscrolls(true);
		labelProjectCode = new javax.swing.JLabel();
		textFieldProjectCode = new javax.swing.JTextField();
		textFieldProjectCode.setColumns(10);
		labelProjectDesc = new javax.swing.JLabel();
		projectDescArea = new javax.swing.JScrollPane();
		textAreaProjectDescription = new javax.swing.JTextArea();
		labelStartDate = new javax.swing.JLabel();
		dateChooserStartDate = new com.toedter.calendar.JDateChooser();
		labelEndDate = new javax.swing.JLabel();
		dateChooserEndDate = new com.toedter.calendar.JDateChooser();
		labelBudgetAmt = new javax.swing.JLabel();
		textFieldBudgetAmount = new javax.swing.JTextField();
		dropdownCurrency = new javax.swing.JComboBox<>();
		labelProjectName = new javax.swing.JLabel();
		textFieldProjectName = new javax.swing.JTextField();
		jSeparator1 = new javax.swing.JSeparator();
		labelRevisedStartDate = new javax.swing.JLabel();
		labelRevisedStartDate.setEnabled(false);
		dateChooserRevisedStartDate = new com.toedter.calendar.JDateChooser();
		dateChooserRevisedStartDate.setEnabled(false);
		dateChooserRevisedStartDate.getCalendarButton().setBackground(SystemColor.activeCaptionBorder);
		dateChooserRevisedStartDate.getCalendarButton().setEnabled(false);
		labelRevisedEndDate = new javax.swing.JLabel();
		labelRevisedEndDate.setEnabled(false);
		datechooserRevisedEndDate = new com.toedter.calendar.JDateChooser();
		datechooserRevisedEndDate.setEnabled(false);
		datechooserRevisedEndDate.setBackground(Color.LIGHT_GRAY);
		datechooserRevisedEndDate.getCalendarButton().setEnabled(false);
		labelRevisedBudgetAmount = new javax.swing.JLabel();
		labelRevisedBudgetAmount.setEnabled(false);
		textFieldRevisedBudgetAmt = new javax.swing.JTextField();
		textFieldRevisedBudgetAmt.setEnabled(false);
		textFieldRevisedBudgetAmt.setEditable(false);
		dropdownRevisedCurrency = new javax.swing.JComboBox<>();
		dropdownRevisedCurrency.setEnabled(false);
		buttonAddEntry = new javax.swing.JButton();
		buttonAddEntry.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				performProjectAddEntry();
			}

			private void performProjectAddEntry() {
				final BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				final ProjectIdentifier projectIdentifier = buildProjectIdentifier();
				basePersistenceHelpers.createProjectIdentifier(projectIdentifier);
			}

			private ProjectIdentifier buildProjectIdentifier() {
				ProjectIdentifier projectIdentifier = new ProjectIdentifier();
				ProjectIdentifierPK id = new ProjectIdentifierPK();
				id.setProjectId(textFieldProjectCode.getText());
				id.setProjectName(textFieldProjectName.getText());
				projectIdentifier.setId(id);
				projectIdentifier.setProjectAmountCurrency(String.valueOf(dropdownCurrency.getSelectedItem()));
				projectIdentifier.setProjectBudgetAmt(new BigDecimal(textFieldBudgetAmount.getText()));
				projectIdentifier.setProjectDesc(textAreaProjectDescription.getText());
				projectIdentifier.setProjectEndDate(dateChooserEndDate.getDate());
				projectIdentifier.setProjectStrtDate(dateChooserStartDate.getDate());
				return projectIdentifier;
			}
		});
		buttonAddEntry.setAction(action);
		buttonCancel = new javax.swing.JButton();
		buttonCancel.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});
		buttonReset = new javax.swing.JButton();
		buttonReset.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				textFieldProjectCode.setText(null);
				textFieldProjectName.setText(null);
				textAreaProjectDescription.setText(null);
				textFieldBudgetAmount.setText(null);
				dateChooserEndDate.setDate(null);
				dateChooserStartDate.setDate(null);
				dropdownCurrency.setSelectedIndex(0);
			}
		});
		panelUpdateEntry = new javax.swing.JPanel();
		panelUpdateEntry.addPropertyChangeListener(new PropertyChangeListener() {
			public void propertyChange(PropertyChangeEvent evt) {

				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				List<ProjectIdentifier> projectIndentifiersList = basePersistenceHelpers
						.retrieveProjectIdentifiers(null);
				dropdownProjectCode.removeAllItems();
				dropdownProjectName.removeAllItems();
				for (ProjectIdentifier projectIdentifier : projectIndentifiersList) {
					dropdownProjectCode.addItem(projectIdentifier.getId().getProjectId());
					dropdownProjectName.addItem(projectIdentifier.getId().getProjectName());
				}

			}
		});

		lebelUpdateProjName = new javax.swing.JLabel();
		labelUpdateProjectId = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		DescriptionPane = new javax.swing.JScrollPane();
		textAreaDescription = new javax.swing.JTextArea();
		jLabel16 = new javax.swing.JLabel();
		initialStartDate = new com.toedter.calendar.JDateChooser();
		initialStartDate.getCalendarButton().setEnabled(false);
		jLabel17 = new javax.swing.JLabel();
		initialEndDate = new com.toedter.calendar.JDateChooser();
		initialEndDate.getCalendarButton().setEnabled(false);
		jLabel18 = new javax.swing.JLabel();
		initialBudgetAmount = new javax.swing.JTextField();
		initialBudgetAmount.setEditable(false);
		initialCurrency = new javax.swing.JComboBox<>();
		initialCurrency.setEnabled(false);
		jLabel19 = new javax.swing.JLabel();
		revisedStartDate = new com.toedter.calendar.JDateChooser();
		jLabel20 = new javax.swing.JLabel();
		revisedEndDate = new com.toedter.calendar.JDateChooser();
		jLabel21 = new javax.swing.JLabel();
		revisedBudgetAmount = new javax.swing.JTextField();
		revisedCurrency = new javax.swing.JComboBox<>();
		jButton4 = new javax.swing.JButton();
		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				projectIdentifierRetrievedForUpdate
						.setProjectRevisedAmountCurrency(revisedCurrency.getSelectedItem().toString());
				projectIdentifierRetrievedForUpdate
						.setProjectRevisedBudgetAmt(new BigDecimal(revisedBudgetAmount.getText()));
				projectIdentifierRetrievedForUpdate.setProjectRevisedStrtDate(revisedStartDate.getDate());
				projectIdentifierRetrievedForUpdate.setProjectRevisedEndDate(revisedEndDate.getDate());
				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				basePersistenceHelpers.updateProjectIdentifier(projectIdentifierRetrievedForUpdate);
			}
		});
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		dropdownProjectName = new javax.swing.JComboBox<>();
		dropdownProjectCode = new javax.swing.JComboBox<>();
		jSeparator2 = new javax.swing.JSeparator();
		panelCloseEntry = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		labelCompanyCopyrights.setText("(c) Intuitive Technologies & Solutions | All rights reserved");

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel1.setText("Project Entry Details ");

		projectEntry.setBorder(new MatteBorder(1, 1, 1, 1, (Color) new Color(0, 0, 0)));

		panelNewEntry.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		labelProjectCode.setText("Project Code ");

		textFieldProjectCode.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		labelProjectDesc.setText("Description");

		textAreaProjectDescription.setColumns(20);
		textAreaProjectDescription.setRows(10);
		projectDescArea.setViewportView(textAreaProjectDescription);

		labelStartDate.setText("Start Date");

		labelEndDate.setText("End Date");

		labelBudgetAmt.setText("Budget Amount");

		dropdownCurrency
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		labelProjectName.setText("Project Name ");

		textFieldProjectName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});

		labelRevisedStartDate.setText("Revised Start Date");

		labelRevisedEndDate.setText("Revised End Date");

		labelRevisedBudgetAmount.setText("Revised Budget Amount");

		dropdownRevisedCurrency
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		buttonAddEntry.setText("Add Entry");

		buttonCancel.setText("Cancel");

		buttonReset.setText("Reset");

		javax.swing.GroupLayout gl_panelNewEntry = new javax.swing.GroupLayout(panelNewEntry);
		gl_panelNewEntry.setHorizontalGroup(
			gl_panelNewEntry.createParallelGroup(Alignment.TRAILING)
				.addGroup(gl_panelNewEntry.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.TRAILING)
							.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addGroup(gl_panelNewEntry.createSequentialGroup()
								.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.LEADING)
									.addComponent(labelProjectCode)
									.addComponent(labelProjectDesc)
									.addComponent(labelStartDate)
									.addComponent(labelEndDate)
									.addComponent(labelBudgetAmt)
									.addComponent(labelProjectName))
								.addGap(18)
								.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.TRAILING, false)
									.addComponent(textFieldProjectCode)
									.addComponent(projectDescArea, GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
									.addComponent(dateChooserStartDate, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(dateChooserEndDate, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addGroup(gl_panelNewEntry.createSequentialGroup()
										.addComponent(textFieldBudgetAmount)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(dropdownCurrency, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE))
									.addComponent(textFieldProjectName)))
							.addGroup(gl_panelNewEntry.createSequentialGroup()
								.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.LEADING)
									.addComponent(labelRevisedStartDate)
									.addComponent(labelRevisedEndDate)
									.addComponent(labelRevisedBudgetAmount))
								.addGap(18)
								.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.TRAILING, false)
									.addGroup(gl_panelNewEntry.createSequentialGroup()
										.addComponent(textFieldRevisedBudgetAmt, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(dropdownRevisedCurrency, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE))
									.addComponent(datechooserRevisedEndDate, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(dateChooserRevisedStartDate, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addGroup(Alignment.TRAILING, gl_panelNewEntry.createSequentialGroup()
							.addComponent(buttonAddEntry)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(buttonReset)
							.addGap(10)
							.addComponent(buttonCancel)))
					.addContainerGap())
		);
		gl_panelNewEntry.setVerticalGroup(
			gl_panelNewEntry.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panelNewEntry.createSequentialGroup()
					.addGap(7)
					.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.BASELINE)
						.addComponent(labelProjectName)
						.addComponent(textFieldProjectName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.BASELINE)
						.addComponent(labelProjectCode)
						.addComponent(textFieldProjectCode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.LEADING)
						.addComponent(labelProjectDesc)
						.addComponent(projectDescArea, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE))
					.addGap(26)
					.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.TRAILING)
						.addComponent(dateChooserStartDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(labelStartDate))
					.addGap(18)
					.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.TRAILING)
						.addComponent(dateChooserEndDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(labelEndDate))
					.addGap(18)
					.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.TRAILING)
						.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.BASELINE)
							.addComponent(textFieldBudgetAmount, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addComponent(dropdownCurrency, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addComponent(labelBudgetAmt))
					.addGap(18)
					.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(32)
					.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.TRAILING)
						.addComponent(dateChooserRevisedStartDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(labelRevisedStartDate))
					.addGap(18)
					.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.TRAILING)
						.addComponent(datechooserRevisedEndDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(labelRevisedEndDate))
					.addGap(18)
					.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.TRAILING)
						.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.BASELINE)
							.addComponent(textFieldRevisedBudgetAmt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addComponent(dropdownRevisedCurrency, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addComponent(labelRevisedBudgetAmount))
					.addPreferredGap(ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
					.addGroup(gl_panelNewEntry.createParallelGroup(Alignment.BASELINE)
						.addComponent(buttonAddEntry)
						.addComponent(buttonCancel)
						.addComponent(buttonReset))
					.addGap(22))
		);
		panelNewEntry.setLayout(gl_panelNewEntry);

		projectEntry.addTab("New Entry", panelNewEntry);

		lebelUpdateProjName.setText("Project Name ");

		labelUpdateProjectId.setText("Project Code ");

		jLabel15.setText("Description");

		textAreaDescription.setColumns(20);
		textAreaDescription.setRows(5);
		DescriptionPane.setViewportView(textAreaDescription);

		jLabel16.setText("Start Date");

		jLabel17.setText("End Date");

		jLabel18.setText("Budget Amount");

		initialCurrency
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		jLabel19.setText("Revised Start Date");

		jLabel20.setText("Revised End Date");

		jLabel21.setText("Revised Budget Amount");

		revisedCurrency
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		jButton4.setText("Update Entry");

		jButton5.setText("Reset");

		jButton6.setText("Cancel");

		dropdownProjectName.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		dropdownProjectCode.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		button = new JButton("...");
		button.setBorder(new LineBorder(new Color(0, 0, 0)));
		button.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dropdownProjectName.setEnabled(false);
				dropdownProjectCode.setEnabled(false);
				final String projectNameSelected = (String) dropdownProjectName.getSelectedItem();
				final String projectCodeSelected = (String) dropdownProjectCode.getSelectedItem();

				populateProjectDetails(projectNameSelected, projectCodeSelected);

			}

			private void populateProjectDetails(String projectNameSelected, String projectCodeSelected) {
				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();

				ProjectIdentifierPK id = new ProjectIdentifierPK();
				id.setProjectId(projectCodeSelected);
				id.setProjectName(projectNameSelected);
				projectIdentifierRetrievedForUpdate = basePersistenceHelpers.retrieveProjectIdentifierDetails(id);
				if (projectIdentifierRetrievedForUpdate != null) {
					dropdownProjectName.setSelectedItem(projectIdentifierRetrievedForUpdate.getId().getProjectName());
					dropdownProjectCode.setSelectedItem(projectIdentifierRetrievedForUpdate.getId().getProjectId());
					textAreaDescription.setText(projectIdentifierRetrievedForUpdate.getProjectDesc());
					initialStartDate.setDate(projectIdentifierRetrievedForUpdate.getProjectStrtDate());
					initialEndDate.setDate(projectIdentifierRetrievedForUpdate.getProjectEndDate());
					initialBudgetAmount
							.setText(String.valueOf(projectIdentifierRetrievedForUpdate.getProjectBudgetAmt()));
					initialCurrency.setSelectedItem(projectIdentifierRetrievedForUpdate.getProjectAmountCurrency());
				}

			}
		});

		JSeparator separator = new JSeparator();

		javax.swing.GroupLayout gl_panelUpdateEntry = new javax.swing.GroupLayout(panelUpdateEntry);
		gl_panelUpdateEntry.setHorizontalGroup(
			gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panelUpdateEntry.createSequentialGroup()
					.addContainerGap()
					.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.TRAILING)
						.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGroup(gl_panelUpdateEntry.createSequentialGroup()
							.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
								.addComponent(labelUpdateProjectId)
								.addComponent(jLabel15)
								.addComponent(jLabel16)
								.addComponent(lebelUpdateProjName))
							.addGap(27)
							.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
								.addGroup(gl_panelUpdateEntry.createSequentialGroup()
									.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.TRAILING)
										.addComponent(dropdownProjectName, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(dropdownProjectCode, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE))
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(button, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
								.addComponent(DescriptionPane, GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
								.addComponent(initialStartDate, GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
								.addComponent(initialEndDate, GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
								.addGroup(gl_panelUpdateEntry.createSequentialGroup()
									.addComponent(initialBudgetAmount, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(initialCurrency, 0, 88, Short.MAX_VALUE))))
						.addComponent(jLabel17)
						.addComponent(jLabel18)
						.addComponent(separator, GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
						.addGroup(gl_panelUpdateEntry.createSequentialGroup()
							.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel19)
								.addComponent(jLabel20))
							.addGap(18)
							.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
								.addComponent(revisedEndDate, GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
								.addComponent(revisedStartDate, GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
						.addGroup(gl_panelUpdateEntry.createSequentialGroup()
							.addComponent(jLabel21)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(revisedBudgetAmount, GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(revisedCurrency, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE))
						.addGroup(gl_panelUpdateEntry.createSequentialGroup()
							.addComponent(jButton4)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jButton5)
							.addGap(10)
							.addComponent(jButton6)))
					.addContainerGap())
		);
		gl_panelUpdateEntry.setVerticalGroup(
			gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panelUpdateEntry.createSequentialGroup()
					.addContainerGap(47, Short.MAX_VALUE)
					.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.TRAILING, false)
						.addGroup(gl_panelUpdateEntry.createSequentialGroup()
							.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
								.addComponent(lebelUpdateProjName)
								.addComponent(dropdownProjectName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(19)
							.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.BASELINE)
								.addComponent(dropdownProjectCode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(labelUpdateProjectId)))
						.addComponent(button, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addGap(18)
					.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel15)
						.addComponent(DescriptionPane, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE))
					.addGap(25)
					.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel16)
						.addComponent(initialStartDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel17)
						.addComponent(initialEndDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel18)
						.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.BASELINE)
							.addComponent(initialBudgetAmount, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addComponent(initialCurrency, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addGap(8)
					.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_panelUpdateEntry.createSequentialGroup()
							.addGap(26)
							.addComponent(separator, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addGap(18)
							.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel19)
								.addComponent(revisedStartDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(18)
							.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel20)
								.addComponent(revisedEndDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(18)
							.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel21)
								.addComponent(revisedBudgetAmount, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(revisedCurrency, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
						.addGroup(gl_panelUpdateEntry.createSequentialGroup()
							.addGap(114)
							.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addGap(127)
					.addGroup(gl_panelUpdateEntry.createParallelGroup(Alignment.BASELINE)
						.addComponent(jButton4)
						.addComponent(jButton6)
						.addComponent(jButton5))
					.addGap(27))
		);
		panelUpdateEntry.setLayout(gl_panelUpdateEntry);

		projectEntry.addTab("Update Entry", panelUpdateEntry);

		JLabel label = new JLabel();
		label.setText("Project Name ");

		JLabel label_1 = new JLabel();
		label_1.setText("Project Code ");

		JLabel label_2 = new JLabel();
		label_2.setText("Budget Amount");

		budgetAmountDelete = new JTextField();
		budgetAmountDelete.setEditable(false);

		JComboBox<String> currencyDelete = new JComboBox<String>();
		currencyDelete.setEnabled(false);

		JDateChooser endateDelete = new JDateChooser();
		endateDelete.getCalendarButton().setEnabled(false);

		JLabel label_3 = new JLabel();
		label_3.setText("End Date");

		JLabel label_4 = new JLabel();
		label_4.setText("Start Date");

		JDateChooser startDateDelete = new JDateChooser();
		startDateDelete.getCalendarButton().setEnabled(false);

		JTextArea textAreaDescriptionDelete = new JTextArea();
		textAreaDescriptionDelete.setEditable(false);
		textAreaDescriptionDelete.setRows(5);
		textAreaDescriptionDelete.setColumns(20);

		JLabel label_5 = new JLabel();
		label_5.setText("Description");

		JComboBox<String> dropdownProjectIdDelete = new JComboBox<String>();
		JComboBox<String> dropdownProjectNameDelete = new JComboBox<String>();
		panelCloseEntry.addPropertyChangeListener(new PropertyChangeListener() {
			public void propertyChange(PropertyChangeEvent evt) {
				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				List<ProjectIdentifier> projectIndentifiersList = basePersistenceHelpers
						.retrieveProjectIdentifiers(null);
				dropdownProjectIdDelete.removeAllItems();
				dropdownProjectNameDelete.removeAllItems();
				for (ProjectIdentifier projectIdentifier : projectIndentifiersList) {
					dropdownProjectIdDelete.addItem(projectIdentifier.getId().getProjectId());
					dropdownProjectNameDelete.addItem(projectIdentifier.getId().getProjectName());
				}

			}
		});
		JButton populateDeleteDetails = new JButton("...");
		populateDeleteDetails.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				final String projectNameSelected = (String) dropdownProjectNameDelete.getSelectedItem();
				final String projectCodeSelected = (String) dropdownProjectIdDelete.getSelectedItem();

				populateProjectDetails(projectNameSelected, projectCodeSelected);

			}

			private void populateProjectDetails(String projectNameSelected, String projectCodeSelected) {
				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();

				ProjectIdentifierPK id = new ProjectIdentifierPK();
				id.setProjectId(projectCodeSelected);
				id.setProjectName(projectNameSelected);
				projectIdentifierRetrievedForDelete = basePersistenceHelpers.retrieveProjectIdentifierDetails(id);
				if (projectIdentifierRetrievedForDelete != null) {
					dropdownProjectNameDelete
							.setSelectedItem(projectIdentifierRetrievedForDelete.getId().getProjectName());
					dropdownProjectIdDelete.setSelectedItem(projectIdentifierRetrievedForDelete.getId().getProjectId());
					textAreaDescriptionDelete.setText(projectIdentifierRetrievedForDelete.getProjectDesc());
					startDateDelete.setDate(projectIdentifierRetrievedForDelete.getProjectStrtDate());
					endateDelete.setDate(projectIdentifierRetrievedForDelete.getProjectEndDate());
					budgetAmountDelete
							.setText(String.valueOf(projectIdentifierRetrievedForDelete.getProjectBudgetAmt()));
					currencyDelete.setSelectedItem(projectIdentifierRetrievedForDelete.getProjectAmountCurrency());
				}

			}
		});
		
		btnCloseEntry = new JButton("Close Entry");
		btnCloseEntry.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				basePersistenceHelpers.deleteProjectIdentifier(projectIdentifierRetrievedForDelete);
			}
		});
		
		btnReset = new JButton("Reset");
		
		btnCancel = new JButton("Cancel");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(panelCloseEntry);
		jPanel3Layout.setHorizontalGroup(
			jPanel3Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(label, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
								.addComponent(label_1, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE))
							.addGap(27)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(dropdownProjectNameDelete, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE)
								.addComponent(dropdownProjectIdDelete, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(populateDeleteDetails, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
						.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(label_3, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
								.addComponent(label_2, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(endateDelete, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 264, GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
									.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(btnCloseEntry)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(btnReset)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(btnCancel))
									.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(budgetAmountDelete, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.UNRELATED)
										.addComponent(currencyDelete, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)))))
						.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(label_4, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
								.addComponent(label_5, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(textAreaDescriptionDelete)
								.addComponent(startDateDelete, GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))))
					.addContainerGap())
		);
		jPanel3Layout.setVerticalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addGap(23)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addGap(14)
							.addComponent(label))
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addGap(11)
							.addComponent(dropdownProjectNameDelete, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addGap(27)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(dropdownProjectIdDelete, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(label_1)))
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addGap(11)
							.addComponent(populateDeleteDetails, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
					.addGap(28)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(textAreaDescriptionDelete, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
						.addComponent(label_5))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(startDateDelete, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(label_4))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(endateDelete, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(label_3))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(label_2)
						.addComponent(budgetAmountDelete, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(currencyDelete, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(btnCloseEntry)
						.addComponent(btnReset)
						.addComponent(btnCancel))
					.addGap(26))
		);
		panelCloseEntry.setLayout(jPanel3Layout);

		projectEntry.addTab("Close Entry", panelCloseEntry);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel1)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(labelCompanyCopyrights)
								.addComponent(projectEntry, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jLabel6)
							.addGap(0)
							.addComponent(filler1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGap(10)
							.addComponent(jLabel1)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(projectEntry, GroupLayout.PREFERRED_SIZE, 702, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
							.addGap(152)
							.addComponent(filler1, GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
							.addGap(180)
							.addComponent(jLabel6)))
					.addGap(18)
					.addComponent(labelCompanyCopyrights)
					.addGap(27))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField3ActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	/**
	 * jComboBox
	 * 
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ProjectEntry().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.Box.Filler filler1;
	private javax.swing.JButton buttonAddEntry;
	private javax.swing.JButton buttonCancel;
	private javax.swing.JButton buttonReset;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private com.toedter.calendar.JCalendar jCalendar1;
	private javax.swing.JComboBox<String> dropdownCurrency;
	private javax.swing.JComboBox<String> dropdownRevisedCurrency;
	private javax.swing.JComboBox<String> initialCurrency;
	private javax.swing.JComboBox<String> revisedCurrency;
	private javax.swing.JComboBox<String> dropdownProjectName;
	private javax.swing.JComboBox<String> dropdownProjectCode;
	private com.toedter.calendar.JDateChooser dateChooserStartDate;
	private com.toedter.calendar.JDateChooser dateChooserEndDate;
	private com.toedter.calendar.JDateChooser dateChooserRevisedStartDate;
	private com.toedter.calendar.JDateChooser datechooserRevisedEndDate;
	private com.toedter.calendar.JDateChooser initialStartDate;
	private com.toedter.calendar.JDateChooser initialEndDate;
	private com.toedter.calendar.JDateChooser revisedStartDate;
	private com.toedter.calendar.JDateChooser revisedEndDate;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel labelCompanyCopyrights;
	private javax.swing.JLabel labelRevisedEndDate;
	private javax.swing.JLabel labelRevisedBudgetAmount;
	private javax.swing.JLabel lebelUpdateProjName;
	private javax.swing.JLabel labelUpdateProjectId;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel labelProjectCode;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel labelProjectDesc;
	private javax.swing.JLabel labelStartDate;
	private javax.swing.JLabel labelEndDate;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel labelBudgetAmt;
	private javax.swing.JLabel labelProjectName;
	private javax.swing.JLabel labelRevisedStartDate;
	private javax.swing.JPanel panelNewEntry;
	private javax.swing.JPanel panelUpdateEntry;
	private javax.swing.JPanel panelCloseEntry;
	private javax.swing.JScrollPane projectDescArea;
	private javax.swing.JScrollPane DescriptionPane;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JTabbedPane jTabbedPane5;
	private javax.swing.JTextArea textAreaProjectDescription;
	private javax.swing.JTextArea textAreaDescription;
	private javax.swing.JTextField textFieldProjectCode;
	private javax.swing.JTextField textFieldBudgetAmount;
	private javax.swing.JTextField textFieldProjectName;
	private javax.swing.JTextField textFieldRevisedBudgetAmt;
	private javax.swing.JTextField initialBudgetAmount;
	private javax.swing.JTextField revisedBudgetAmount;
	private javax.swing.JTabbedPane projectEntry;
	private final Action action = new SwingAction();
	private JButton button;

	// variables for local purpose//
	ProjectIdentifier projectIdentifierRetrievedForUpdate = null;
	ProjectIdentifier projectIdentifierRetrievedForDelete = null;

	private JTextField budgetAmountDelete;
	private JButton btnCloseEntry;
	private JButton btnReset;
	private JButton btnCancel;

	// End of variables declaration//GEN-END:variables
	private class SwingAction extends AbstractAction {
		/**
		 * 
		 */
		private static final long serialVersionUID = 1L;

		public SwingAction() {
			putValue(NAME, "SwingAction");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}

		public void actionPerformed(ActionEvent e) {
		}
	}
}
