/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ourits.jobcosting.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import java.util.List;

import com.ourits.jobcosting.entities.ProjectIdentifier;
import com.ourits.jobcosting.entities.ProjectIdentifierPK;
import com.ourits.jobcosting.entities.SubProjectIdentifier;
import com.ourits.jobcosting.entities.SubProjectIdentifierPK;
import com.ourits.jobcosting.persistencehelpers.BasePersistenceHelpers;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Other guest
 */
public class SubProjectEntry extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected SubProjectIdentifier subProjectIdentifierRetrievedForUpdate;

	/**
	 * Creates new form NewJFrame
	 */
	public SubProjectEntry() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane5 = new javax.swing.JTabbedPane();
		jCalendar1 = new com.toedter.calendar.JCalendar();
		jLabel10 = new javax.swing.JLabel();
		filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 150),
				new java.awt.Dimension(32767, 150));
		jLabel6 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		subprojectEntry = new javax.swing.JTabbedPane();
		addNewEntryPanel = new javax.swing.JPanel();

		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		textAreaDescriptionAdd = new javax.swing.JTextArea();
		jLabel4 = new javax.swing.JLabel();
		startDateAdd = new com.toedter.calendar.JDateChooser();
		jLabel5 = new javax.swing.JLabel();
		endDateAdd = new com.toedter.calendar.JDateChooser();
		jLabel7 = new javax.swing.JLabel();
		budgetAmountAdd = new javax.swing.JTextField();
		dropdownCurrency = new javax.swing.JComboBox<>();
		jLabel8 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel9 = new javax.swing.JLabel();
		jLabel9.setEnabled(false);
		revisedStartDateAdd = new com.toedter.calendar.JDateChooser();
		revisedStartDateAdd.getCalendarButton().setEnabled(false);
		jLabel11 = new javax.swing.JLabel();
		jLabel11.setEnabled(false);
		revisedEndDateAdd = new com.toedter.calendar.JDateChooser();
		revisedEndDateAdd.getCalendarButton().setEnabled(false);
		jLabel12 = new javax.swing.JLabel();
		jLabel12.setEnabled(false);
		revisedBugetAdd = new javax.swing.JTextField();
		revisedBugetAdd.setEnabled(false);
		revisedBugetAdd.setEditable(false);
		jComboBox2 = new javax.swing.JComboBox<>();
		jComboBox2.setEnabled(false);
		buttonAddSubProjectEntry = new javax.swing.JButton();
		buttonAddSubProjectEntry.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				performSubProjectAddEntry();
			}

			private void performSubProjectAddEntry() {
				final BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				final SubProjectIdentifier subProjectIdentifier = buildSubProjectIdentifier();
				basePersistenceHelpers.createSubProjectIdentifier(subProjectIdentifier);
			}

			private SubProjectIdentifier buildSubProjectIdentifier() {
				SubProjectIdentifier subProjectIdentifier = new SubProjectIdentifier();
				SubProjectIdentifierPK id = new SubProjectIdentifierPK();
				id.setProjectId(dropdownProjectIdAdd.getSelectedItem().toString());
				id.setProjectName(dropdownProjectNameAdd.getSelectedItem().toString());
				id.setSubProjectId(subProjectCodeAdd.getText());
				id.setSubProjectName(subProjectNameAdd.getText());
				subProjectIdentifier.setId(id);
				subProjectIdentifier.setContractor(contractorAdd.getText());
				subProjectIdentifier.setPercentageCompletion(new BigDecimal(textPercentageCompletionAdd.getText()));
				subProjectIdentifier.setSubProjectAmountCurrency(dropdownCurrency.getSelectedItem().toString());
				subProjectIdentifier.setSubProjectBudgetAmt(new BigDecimal(budgetAmountAdd.getText()));
				subProjectIdentifier.setSubProjectDesc(textAreaDescriptionAdd.getText());
				subProjectIdentifier.setSubProjectEndDate(startDateAdd.getDate());
				subProjectIdentifier.setSubProjectStrtDate(endDateAdd.getDate());
				ProjectIdentifier projectIdentifier = new ProjectIdentifier();
				ProjectIdentifierPK FKid = new ProjectIdentifierPK();
				FKid.setProjectId(dropdownProjectIdAdd.getSelectedItem().toString());
				FKid.setProjectName(dropdownProjectNameAdd.getSelectedItem().toString());
				projectIdentifier.setId(FKid);

				subProjectIdentifier.setProjectIdentifier(projectIdentifier);
				return subProjectIdentifier;
			}
		});
		buttonCancel = new javax.swing.JButton();
		buttonReset = new javax.swing.JButton();
		dropdownProjectNameAdd = new javax.swing.JComboBox<>();
		dropdownProjectIdAdd = new javax.swing.JComboBox<>();
		jLabel23 = new javax.swing.JLabel();
		subProjectCodeAdd = new javax.swing.JTextField();
		jLabel30 = new javax.swing.JLabel();
		contractorAdd = new javax.swing.JTextField();
		jLabel31 = new javax.swing.JLabel();
		textPercentageCompletionAdd = new javax.swing.JTextField();
		jLabel32 = new javax.swing.JLabel();
		jLabel33 = new javax.swing.JLabel();
		subProjectNameAdd = new javax.swing.JTextField();
		jButton16 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jLabel47 = new javax.swing.JLabel();
		jComboBox18 = new javax.swing.JComboBox<>();
		jLabel48 = new javax.swing.JLabel();
		jComboBox19 = new javax.swing.JComboBox<>();
		jLabel49 = new javax.swing.JLabel();
		jLabel50 = new javax.swing.JLabel();
		jLabel51 = new javax.swing.JLabel();
		jTextField16 = new javax.swing.JTextField();
		jLabel52 = new javax.swing.JLabel();
		jTextField17 = new javax.swing.JTextField();
		jLabel53 = new javax.swing.JLabel();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTextArea5 = new javax.swing.JTextArea();
		jLabel54 = new javax.swing.JLabel();
		jDateChooser15 = new com.toedter.calendar.JDateChooser();
		jLabel55 = new javax.swing.JLabel();
		jDateChooser16 = new com.toedter.calendar.JDateChooser();
		jLabel56 = new javax.swing.JLabel();
		jTextField18 = new javax.swing.JTextField();
		jComboBox20 = new javax.swing.JComboBox<>();
		jSeparator4 = new javax.swing.JSeparator();
		jLabel57 = new javax.swing.JLabel();
		jDateChooser17 = new com.toedter.calendar.JDateChooser();
		jLabel58 = new javax.swing.JLabel();
		jDateChooser18 = new com.toedter.calendar.JDateChooser();
		jLabel59 = new javax.swing.JLabel();
		jTextField19 = new javax.swing.JTextField();
		jComboBox21 = new javax.swing.JComboBox<>();
		jComboBox22 = new javax.swing.JComboBox<>();
		jComboBox23 = new javax.swing.JComboBox<>();
		jLabel14 = new javax.swing.JLabel();
		jButton22 = new javax.swing.JButton();
		jButton23 = new javax.swing.JButton();
		jButton24 = new javax.swing.JButton();
		jButton25 = new javax.swing.JButton();
		// TODO
		addNewEntryPanel.addPropertyChangeListener(new PropertyChangeListener() {
			public void propertyChange(PropertyChangeEvent evt) {

				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				List<ProjectIdentifier> projectIndentifiersList = basePersistenceHelpers
						.retrieveProjectIdentifiers(null);
				dropdownProjectIdAdd.removeAllItems();
				dropdownProjectNameAdd.removeAllItems();
				for (ProjectIdentifier projectIdentifier : projectIndentifiersList) {
					dropdownProjectIdAdd.addItem(projectIdentifier.getId().getProjectId());
					dropdownProjectNameAdd.addItem(projectIdentifier.getId().getProjectName());
				}

			}
		});
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jLabel10.setText("(c) Intuitive Technologies & Solutions | All rights reserved");

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel1.setText("Sub-Project Entry Details ");

		subprojectEntry.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED,
				java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray,
				java.awt.Color.lightGray));

		jLabel2.setText("Project Code ");

		jLabel3.setText("Description");

		textAreaDescriptionAdd.setColumns(20);
		textAreaDescriptionAdd.setRows(5);
		jScrollPane1.setViewportView(textAreaDescriptionAdd);

		jLabel4.setText("Start Date");

		jLabel5.setText("End Date");

		jLabel7.setText("Budget Amount");

		dropdownCurrency
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		jLabel8.setText("Project Name ");

		jLabel9.setText("Revised Start Date");

		jLabel11.setText("Revised End Date");

		jLabel12.setText("Revised Budget Amount");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		buttonAddSubProjectEntry.setText("Add Sub-Project Entry");

		buttonCancel.setText("Cancel");

		buttonReset.setText("Reset");

		dropdownProjectNameAdd.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		dropdownProjectIdAdd.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel23.setText("Sub Project Code ");

		jLabel30.setText("Contractor");

		jLabel31.setText("% completion");

		jLabel32.setText("%");

		jLabel33.setText("Sub Project Name ");

		jButton16.setText("jButton7");

		jButton17.setText("jButton7");

		javax.swing.GroupLayout gl_addNewEntryPanel = new javax.swing.GroupLayout(addNewEntryPanel);
		addNewEntryPanel.setLayout(gl_addNewEntryPanel);
		gl_addNewEntryPanel.setHorizontalGroup(gl_addNewEntryPanel
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_addNewEntryPanel.createSequentialGroup().addContainerGap()
						.addGroup(gl_addNewEntryPanel
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										gl_addNewEntryPanel
												.createSequentialGroup().addGroup(gl_addNewEntryPanel
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jSeparator1)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																gl_addNewEntryPanel.createSequentialGroup()
																		.addGap(0, 0, Short.MAX_VALUE)
																		.addComponent(buttonAddSubProjectEntry)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(buttonReset).addGap(10, 10, 10)
																		.addComponent(buttonCancel))
														.addGroup(gl_addNewEntryPanel.createSequentialGroup()
																.addGroup(gl_addNewEntryPanel
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(gl_addNewEntryPanel
																				.createSequentialGroup()
																				.addGroup(gl_addNewEntryPanel
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(jLabel9)
																						.addComponent(jLabel11)
																						.addComponent(jLabel12))
																				.addGap(18, 18, 18)
																				.addGroup(gl_addNewEntryPanel
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(revisedEndDateAdd,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								revisedStartDateAdd,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addGroup(gl_addNewEntryPanel
																								.createSequentialGroup()
																								.addComponent(
																										revisedBugetAdd,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										118,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jComboBox2, 0,
																										75,
																										Short.MAX_VALUE))))
																		.addGroup(gl_addNewEntryPanel
																				.createSequentialGroup()
																				.addGroup(gl_addNewEntryPanel
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addGroup(gl_addNewEntryPanel
																								.createSequentialGroup()
																								.addGroup(
																										gl_addNewEntryPanel
																												.createParallelGroup(
																														javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel2)
																												.addComponent(
																														jLabel3)
																												.addComponent(
																														jLabel4)
																												.addComponent(
																														jLabel5)
																												.addComponent(
																														jLabel7)
																												.addComponent(
																														jLabel8))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										gl_addNewEntryPanel
																												.createParallelGroup(
																														javax.swing.GroupLayout.Alignment.LEADING,
																														false)
																												.addComponent(
																														jScrollPane1,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														263,
																														Short.MAX_VALUE)
																												.addComponent(
																														startDateAdd,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addComponent(
																														endDateAdd,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addGroup(
																														javax.swing.GroupLayout.Alignment.TRAILING,
																														gl_addNewEntryPanel
																																.createSequentialGroup()
																																.addComponent(
																																		budgetAmountAdd)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		dropdownCurrency,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		82,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))
																												.addComponent(
																														dropdownProjectNameAdd,
																														0,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addComponent(
																														dropdownProjectIdAdd,
																														0,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								gl_addNewEntryPanel
																										.createSequentialGroup()
																										.addGroup(
																												gl_addNewEntryPanel
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel23)
																														.addComponent(
																																jLabel33))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												gl_addNewEntryPanel
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																textPercentageCompletionAdd,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																77,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																subProjectNameAdd)
																														.addComponent(
																																subProjectCodeAdd))))
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																				.addGroup(gl_addNewEntryPanel
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(jButton16,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								35,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(jButton17,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								35,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
																.addGap(0, 0, Short.MAX_VALUE)))
												.addContainerGap())
								.addGroup(gl_addNewEntryPanel.createSequentialGroup()
										.addGroup(gl_addNewEntryPanel
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel30).addComponent(jLabel31))
										.addGroup(gl_addNewEntryPanel
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(gl_addNewEntryPanel.createSequentialGroup()
														.addGap(112, 112, 112).addComponent(jLabel32).addContainerGap(
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(gl_addNewEntryPanel.createSequentialGroup().addGap(34, 34, 34)
														.addComponent(contractorAdd,
																javax.swing.GroupLayout.PREFERRED_SIZE, 247,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(0, 0, Short.MAX_VALUE)))))));
		gl_addNewEntryPanel.setVerticalGroup(gl_addNewEntryPanel
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_addNewEntryPanel.createSequentialGroup().addGap(6, 6, 6)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel8)
								.addComponent(dropdownProjectNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton17))
						.addGap(18, 18, 18)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(dropdownProjectIdAdd, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton16))
						.addGap(18, 18, 18)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel23).addComponent(subProjectCodeAdd,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel33).addComponent(subProjectNameAdd,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel31)
								.addComponent(textPercentageCompletionAdd, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel32))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel30).addComponent(contractorAdd,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel3)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(26, 26, 26)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(startDateAdd, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4))
						.addGap(18, 18, 18)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(endDateAdd, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5))
						.addGap(18, 18, 18)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(gl_addNewEntryPanel
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(budgetAmountAdd, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(dropdownCurrency, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel7))
						.addGap(37, 37, 37)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(revisedStartDateAdd, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel9))
						.addGap(18, 18, 18)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(revisedEndDateAdd, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel11))
						.addGap(18, 18, 18)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(gl_addNewEntryPanel
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(revisedBugetAdd, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel12))
						.addGap(45, 45, 45)
						.addGroup(gl_addNewEntryPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(buttonAddSubProjectEntry).addComponent(buttonCancel)
								.addComponent(buttonReset))
						.addContainerGap()));

		subprojectEntry.addTab("New Entry", addNewEntryPanel);
		updateEntry = new javax.swing.JPanel();
		updateEntry.addPropertyChangeListener(new PropertyChangeListener() {
			public void propertyChange(PropertyChangeEvent evt) {

				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				List<ProjectIdentifier> projectIndentifiersList = basePersistenceHelpers
						.retrieveProjectIdentifiers(null);
				projectCodeUpdate.removeAllItems();
				projectNameUpdate.removeAllItems();
				for (ProjectIdentifier projectIdentifier : projectIndentifiersList) {
					projectCodeUpdate.addItem(projectIdentifier.getId().getProjectId());
					projectNameUpdate.addItem(projectIdentifier.getId().getProjectName());
				}

			}
		});
		jButton4 = new javax.swing.JButton();
		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				subProjectIdentifierRetrievedForUpdate.setContractor(revisedContractor.getText());
				subProjectIdentifierRetrievedForUpdate
						.setPercentageCompletion(new BigDecimal(percentageCompletionUpdate.getText()));
				subProjectIdentifierRetrievedForUpdate
						.setSubProjectRevisedAmountCurrency(revisedCurrencyAmt.getSelectedItem().toString());
				subProjectIdentifierRetrievedForUpdate
						.setSubProjectRevisedBudgetAmt(new BigDecimal(revisedBudgetAmt.getText()));
				subProjectIdentifierRetrievedForUpdate.setSubProjectRevisedStrtDate(revisedStartDate.getDate());
				subProjectIdentifierRetrievedForUpdate.setSubProjectRevisedEndDate(revisedEndDate.getDate());

				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				basePersistenceHelpers.updateSubProjectIdentifier(subProjectIdentifierRetrievedForUpdate);
			}
		});
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jLabel34 = new javax.swing.JLabel();
		projectNameUpdate = new javax.swing.JComboBox<>();
		jLabel35 = new javax.swing.JLabel();
		projectCodeUpdate = new javax.swing.JComboBox<>();
		jLabel36 = new javax.swing.JLabel();
		jLabel37 = new javax.swing.JLabel();
		jLabel38 = new javax.swing.JLabel();
		percentageCompletionUpdate = new javax.swing.JTextField();
		jLabel39 = new javax.swing.JLabel();
		revisedContractor = new javax.swing.JTextField();
		jLabel40 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		textAreaDescUpdate = new javax.swing.JTextArea();
		jLabel41 = new javax.swing.JLabel();
		initialStartDate = new com.toedter.calendar.JDateChooser();
		initialStartDate.getCalendarButton().setEnabled(false);
		jLabel42 = new javax.swing.JLabel();
		initialEndDate = new com.toedter.calendar.JDateChooser();
		initialEndDate.getCalendarButton().setEnabled(false);
		jLabel43 = new javax.swing.JLabel();
		initialBudgetAmt = new javax.swing.JTextField();
		initialBudgetAmt.setEnabled(false);
		initialBudgetAmt.setEditable(false);
		initialBudgetCurrency = new javax.swing.JComboBox<>();
		initialBudgetCurrency.setEnabled(false);
		jSeparator3 = new javax.swing.JSeparator();
		jLabel44 = new javax.swing.JLabel();
		revisedStartDate = new com.toedter.calendar.JDateChooser();
		jLabel45 = new javax.swing.JLabel();
		revisedEndDate = new com.toedter.calendar.JDateChooser();
		jLabel46 = new javax.swing.JLabel();
		revisedBudgetAmt = new javax.swing.JTextField();
		revisedCurrencyAmt = new javax.swing.JComboBox<>();
		subProjectIdUpdate = new javax.swing.JComboBox<>();
		subProjectIdUpdate.setEnabled(false);
		subprojectNameUpdate = new javax.swing.JComboBox<>();
		subprojectNameUpdate.setEnabled(false);
		jLabel13 = new javax.swing.JLabel();
		populateSubProductsDropdown = new javax.swing.JButton();
		populateSubProductsDropdown.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				projectCodeUpdate.setEnabled(false);
				projectNameUpdate.setEnabled(false);
				final String projectNameSelected = (String) projectNameUpdate.getSelectedItem();
				final String projectCodeSelected = (String) projectCodeUpdate.getSelectedItem();

				retrieveSubProjects(projectNameSelected, projectCodeSelected);
				subprojectNameUpdate.setEnabled(true);
				subProjectIdUpdate.setEnabled(true);

			}

			private void retrieveSubProjects(String projectNameSelected, String projectCodeSelected) {
				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				List<SubProjectIdentifier> subProjectIdentifiersList = basePersistenceHelpers
						.retrieveSubProjectIdentifiers(null);
				subprojectNameUpdate.removeAllItems();
				subProjectIdUpdate.removeAllItems();
				for (SubProjectIdentifier subProjectIdentifier : subProjectIdentifiersList) {
					subProjectIdUpdate.addItem(subProjectIdentifier.getId().getSubProjectId());
					subprojectNameUpdate.addItem(subProjectIdentifier.getId().getSubProjectName());
				}

			}

		});
		populateSubProductDetails = new javax.swing.JButton();
		populateSubProductDetails.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				subprojectNameUpdate.setEnabled(false);
				subProjectIdUpdate.setEnabled(false);
				final String projectNameSelected = (String) projectNameUpdate.getSelectedItem();
				final String projectCodeSelected = (String) projectCodeUpdate.getSelectedItem();
				final String subProjectNameSelected = (String) subprojectNameUpdate.getSelectedItem();
				final String subProjectCodeSelected = (String) subProjectIdUpdate.getSelectedItem();
				populateSubProjectDetails(projectNameSelected, projectCodeSelected, subProjectNameSelected,
						subProjectCodeSelected);

			}

			private void populateSubProjectDetails(String projectNameSelected, String projectCodeSelected,
					String subProjectNameSelected, String subProjectCodeSelected) {

				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();

				SubProjectIdentifierPK id = new SubProjectIdentifierPK();
				id.setProjectId(projectCodeSelected);
				id.setProjectName(projectNameSelected);
				id.setSubProjectId(subProjectCodeSelected);
				id.setSubProjectName(subProjectNameSelected);
				subProjectIdentifierRetrievedForUpdate = basePersistenceHelpers.retrieveSubProjectIdentifierDetails(id);
				if (subProjectIdentifierRetrievedForUpdate != null) {
					projectNameUpdate.setSelectedItem(subProjectIdentifierRetrievedForUpdate.getId().getProjectName());
					projectCodeUpdate.setSelectedItem(subProjectIdentifierRetrievedForUpdate.getId().getProjectId());
					subProjectIdUpdate
							.setSelectedItem(subProjectIdentifierRetrievedForUpdate.getId().getSubProjectId());
					subprojectNameUpdate
							.setSelectedItem(subProjectIdentifierRetrievedForUpdate.getId().getSubProjectName());
					textAreaDescUpdate.setText(subProjectIdentifierRetrievedForUpdate.getSubProjectDesc());
					initialStartDate.setDate(subProjectIdentifierRetrievedForUpdate.getSubProjectStrtDate());
					initialEndDate.setDate(subProjectIdentifierRetrievedForUpdate.getSubProjectEndDate());
					initialBudgetAmt
							.setText(String.valueOf(subProjectIdentifierRetrievedForUpdate.getSubProjectBudgetAmt()));
					initialBudgetCurrency
							.setSelectedItem(subProjectIdentifierRetrievedForUpdate.getSubProjectAmountCurrency());
					revisedContractor.setText(subProjectIdentifierRetrievedForUpdate.getContractor());
					percentageCompletionUpdate
							.setText(subProjectIdentifierRetrievedForUpdate.getPercentageCompletion().toString());
				}

			}
		});

		jButton4.setText("Update Sub-Project Entry");

		jButton5.setText("Reset");

		jButton6.setText("Cancel");

		jLabel34.setText("Project Name ");

		projectNameUpdate.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel35.setText("Project Code ");

		projectCodeUpdate.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel36.setText("Sub Project Code ");

		jLabel37.setText("Sub Project Name ");

		jLabel38.setText("% completion");

		jLabel39.setText("Contractor");

		jLabel40.setText("Description");

		textAreaDescUpdate.setColumns(20);
		textAreaDescUpdate.setRows(5);
		jScrollPane4.setViewportView(textAreaDescUpdate);

		jLabel41.setText("Start Date");

		jLabel42.setText("End Date");

		jLabel43.setText("Budget Amount");

		initialBudgetCurrency
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		jLabel44.setText("Revised Start Date");

		jLabel45.setText("Revised End Date");

		jLabel46.setText("Revised Budget Amount");

		revisedCurrencyAmt
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		subProjectIdUpdate.setModel(new DefaultComboBoxModel(new String[] { "select" }));

		subprojectNameUpdate.setModel(new DefaultComboBoxModel(new String[] { "select" }));

		jLabel13.setText("%");

		populateSubProductsDropdown.setText("jButton7");

		populateSubProductDetails.setText("jButton7");

		javax.swing.GroupLayout gl_updateEntry = new javax.swing.GroupLayout(updateEntry);
		gl_updateEntry.setHorizontalGroup(gl_updateEntry.createParallelGroup(Alignment.LEADING).addGroup(gl_updateEntry
				.createSequentialGroup().addContainerGap()
				.addGroup(gl_updateEntry.createParallelGroup(Alignment.LEADING)
						.addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGroup(gl_updateEntry.createSequentialGroup()
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.LEADING).addComponent(jLabel44)
										.addComponent(jLabel45).addComponent(jLabel46))
								.addGap(18)
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.LEADING, false)
										.addComponent(revisedEndDate, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(revisedStartDate, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(gl_updateEntry.createSequentialGroup()
												.addComponent(revisedBudgetAmt, GroupLayout.PREFERRED_SIZE, 118,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addComponent(revisedCurrencyAmt, GroupLayout.PREFERRED_SIZE, 75,
														GroupLayout.PREFERRED_SIZE))))
						.addGroup(gl_updateEntry.createSequentialGroup()
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.LEADING).addComponent(jLabel39)
										.addComponent(jLabel38))
								.addGap(34).addComponent(revisedContractor, GroupLayout.PREFERRED_SIZE, 247,
										GroupLayout.PREFERRED_SIZE))
						.addGroup(
								gl_updateEntry.createSequentialGroup()
										.addGroup(
												gl_updateEntry
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(gl_updateEntry
																.createParallelGroup(Alignment.LEADING, false)
																.addGroup(gl_updateEntry.createSequentialGroup()
																		.addGroup(gl_updateEntry
																				.createParallelGroup(Alignment.LEADING)
																				.addComponent(jLabel35)
																				.addComponent(jLabel40)
																				.addComponent(jLabel41)
																				.addComponent(jLabel42)
																				.addComponent(jLabel43)
																				.addComponent(jLabel34))
																		.addPreferredGap(ComponentPlacement.RELATED)
																		.addGroup(gl_updateEntry
																				.createParallelGroup(Alignment.TRAILING,
																						false)
																				.addComponent(jScrollPane4,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(initialStartDate,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(initialEndDate,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addGroup(gl_updateEntry
																						.createSequentialGroup()
																						.addComponent(initialBudgetAmt)
																						.addPreferredGap(
																								ComponentPlacement.RELATED)
																						.addComponent(
																								initialBudgetCurrency,
																								GroupLayout.PREFERRED_SIZE,
																								82,
																								GroupLayout.PREFERRED_SIZE))
																				.addComponent(projectNameUpdate, 0,
																						GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(projectCodeUpdate,
																						GroupLayout.PREFERRED_SIZE, 263,
																						GroupLayout.PREFERRED_SIZE)))
																.addGroup(gl_updateEntry.createSequentialGroup()
																		.addComponent(jLabel36).addGap(9)
																		.addGroup(gl_updateEntry
																				.createParallelGroup(Alignment.LEADING)
																				.addGroup(gl_updateEntry
																						.createSequentialGroup()
																						.addPreferredGap(
																								ComponentPlacement.RELATED)
																						.addComponent(
																								percentageCompletionUpdate,
																								GroupLayout.PREFERRED_SIZE,
																								77,
																								GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								ComponentPlacement.RELATED)
																						.addComponent(jLabel13)
																						.addGap(0, 149,
																								Short.MAX_VALUE))
																				.addComponent(subProjectIdUpdate, 0,
																						GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))))
														.addGroup(gl_updateEntry.createSequentialGroup()
																.addComponent(jLabel37)
																.addPreferredGap(ComponentPlacement.RELATED)
																.addComponent(subprojectNameUpdate,
																		GroupLayout.PREFERRED_SIZE, 243,
																		GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(ComponentPlacement.RELATED)
										.addGroup(gl_updateEntry.createParallelGroup(Alignment.LEADING)
												.addComponent(populateSubProductsDropdown, GroupLayout.PREFERRED_SIZE,
														35, GroupLayout.PREFERRED_SIZE)
												.addComponent(populateSubProductDetails, GroupLayout.PREFERRED_SIZE, 35,
														GroupLayout.PREFERRED_SIZE))))
				.addContainerGap())
				.addGroup(gl_updateEntry.createSequentialGroup().addContainerGap(88, Short.MAX_VALUE)
						.addComponent(jButton4).addPreferredGap(ComponentPlacement.RELATED).addComponent(jButton5)
						.addGap(10).addComponent(jButton6).addContainerGap()));
		gl_updateEntry.setVerticalGroup(gl_updateEntry.createParallelGroup(Alignment.LEADING).addGroup(gl_updateEntry
				.createSequentialGroup().addContainerGap()
				.addGroup(gl_updateEntry.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_updateEntry.createSequentialGroup()
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.BASELINE).addComponent(jLabel34)
										.addComponent(projectNameUpdate, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addGap(18)
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.BASELINE).addComponent(jLabel35)
										.addComponent(projectCodeUpdate, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
						.addComponent(populateSubProductsDropdown, GroupLayout.PREFERRED_SIZE, 65,
								GroupLayout.PREFERRED_SIZE))
				.addGap(30)
				.addGroup(gl_updateEntry.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_updateEntry.createSequentialGroup()
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.BASELINE).addComponent(jLabel36)
										.addComponent(subProjectIdUpdate, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.BASELINE)
										.addComponent(subprojectNameUpdate, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel37))
								.addPreferredGap(ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.BASELINE).addComponent(jLabel38)
										.addComponent(jLabel13)
										.addComponent(percentageCompletionUpdate, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.BASELINE).addComponent(jLabel39)
										.addComponent(revisedContractor, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addGap(18)
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.LEADING).addComponent(jLabel40)
										.addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 80,
												GroupLayout.PREFERRED_SIZE))
								.addGap(26)
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.TRAILING)
										.addComponent(initialStartDate, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel41))
								.addGap(18)
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.TRAILING)
										.addComponent(initialEndDate, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel42))
								.addGap(18)
								.addGroup(gl_updateEntry
										.createParallelGroup(Alignment.TRAILING)
										.addGroup(gl_updateEntry.createParallelGroup(Alignment.BASELINE)
												.addComponent(initialBudgetAmt, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(initialBudgetCurrency, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addComponent(jLabel43))
								.addGap(37)
								.addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.TRAILING)
										.addComponent(revisedStartDate, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel44))
								.addGap(18)
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.TRAILING)
										.addComponent(revisedEndDate, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel45))
								.addGap(18)
								.addGroup(gl_updateEntry.createParallelGroup(Alignment.TRAILING)
										.addGroup(gl_updateEntry.createParallelGroup(Alignment.BASELINE)
												.addComponent(revisedBudgetAmt, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(revisedCurrencyAmt, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addComponent(jLabel46))
								.addGap(77))
						.addGroup(
								gl_updateEntry.createSequentialGroup().addGap(1)
										.addComponent(populateSubProductDetails, GroupLayout.PREFERRED_SIZE, 58,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED, 545, Short.MAX_VALUE)
										.addGroup(gl_updateEntry.createParallelGroup(Alignment.BASELINE)
												.addComponent(jButton4).addComponent(jButton6).addComponent(jButton5))
										.addGap(10)))));
		updateEntry.setLayout(gl_updateEntry);

		subprojectEntry.addTab("Update Entry", updateEntry);

		jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED,
				java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray,
				java.awt.Color.lightGray));

		jButton7.setText("Close Sub-Project Entry");

		jButton8.setText("Reset");

		jButton9.setText("Cancel");

		jLabel47.setText("Project Name ");

		jComboBox18.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel48.setText("Project Code ");

		jComboBox19.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel49.setText("Sub Project Code ");

		jLabel50.setText("Sub Project Name ");

		jLabel51.setText("% completion");

		jLabel52.setText("Contractor");

		jLabel53.setText("Description");

		jTextArea5.setColumns(20);
		jTextArea5.setRows(5);
		jScrollPane5.setViewportView(jTextArea5);

		jLabel54.setText("Start Date");

		jLabel55.setText("End Date");

		jLabel56.setText("Budget Amount");

		jComboBox20
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		jLabel57.setText("Revised Start Date");

		jLabel58.setText("Revised End Date");

		jLabel59.setText("Revised Budget Amount");

		jComboBox21
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "EUR", "AED", "DHM" }));

		jComboBox22.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jComboBox23.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel14.setText("%");

		jButton22.setText("jButton7");

		jButton23.setText("jButton7");

		jButton24.setText("jButton7");

		jButton25.setText("jButton7");

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jSeparator4).addGroup(jPanel5Layout
												.createSequentialGroup().addGroup(jPanel5Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel5Layout.createSequentialGroup().addGroup(
																jPanel5Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel57).addComponent(jLabel58)
																		.addComponent(jLabel59))
																.addGap(18, 18, 18)
																.addGroup(jPanel5Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addComponent(jDateChooser18,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jDateChooser17,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(jPanel5Layout.createSequentialGroup()
																				.addComponent(jTextField19,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						118,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(jComboBox21,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						75,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(jPanel5Layout.createSequentialGroup()
																.addGroup(jPanel5Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel52).addComponent(jLabel51))
																.addGap(34, 34, 34).addComponent(jTextField17,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 247,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(jPanel5Layout.createSequentialGroup()
																.addGroup(jPanel5Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addGroup(jPanel5Layout.createSequentialGroup()
																				.addGroup(jPanel5Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(jLabel48)
																						.addComponent(jLabel53)
																						.addComponent(jLabel54)
																						.addComponent(jLabel55)
																						.addComponent(jLabel56)
																						.addComponent(jLabel47))
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(jPanel5Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(jScrollPane5)
																						.addComponent(jDateChooser15,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(jDateChooser16,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel5Layout
																										.createSequentialGroup()
																										.addComponent(
																												jTextField18)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jComboBox20,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												82,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(jComboBox18, 0,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(jComboBox19,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								263,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				jPanel5Layout.createSequentialGroup()
																						.addComponent(jLabel49)
																						.addGap(9, 9, 9)
																						.addGroup(jPanel5Layout
																								.createParallelGroup(
																										javax.swing.GroupLayout.Alignment.LEADING)
																								.addGroup(jPanel5Layout
																										.createSequentialGroup()
																										.addComponent(
																												jTextField16,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												77,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel14)
																										.addGap(0, 0,
																												Short.MAX_VALUE))
																								.addComponent(
																										jComboBox22, 0,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE))))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(jPanel5Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jButton22,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				35,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jButton23,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				35,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jButton25,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				35,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(jPanel5Layout.createSequentialGroup()
																.addComponent(jLabel50)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jComboBox23,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 243,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jButton24,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 35,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGap(0, 5, Short.MAX_VALUE)))
								.addContainerGap())
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel5Layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButton7)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton8).addGap(10, 10, 10).addComponent(jButton9)
										.addContainerGap())));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel47)
								.addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton22))
						.addGap(18, 18, 18)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel48)
								.addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton23))
						.addGap(18, 18, 18)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel49)
								.addComponent(jComboBox22, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton25))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jComboBox23, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel50).addComponent(jButton24))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel51).addComponent(jTextField16,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel14))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel52).addComponent(jTextField17,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel53).addComponent(jScrollPane5,
										javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(26, 26, 26)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jDateChooser15, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel54))
						.addGap(18, 18, 18)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jDateChooser16, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel55))
						.addGap(18, 18, 18)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel56))
						.addGap(37, 37, 37)
						.addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jDateChooser17, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel57))
						.addGap(18, 18, 18)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jDateChooser18, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel58))
						.addGap(18, 18, 18)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox21, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel59))
						.addGap(77, 77, 77))
				.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap(653, Short.MAX_VALUE)
								.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton7).addComponent(jButton9).addComponent(jButton8))
								.addGap(10, 10, 10))));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 430, Short.MAX_VALUE)
				.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 692, Short.MAX_VALUE)
				.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))));

		subprojectEntry.addTab("Close Entry", jPanel3);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(12, 12, 12)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jLabel10))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addComponent(subprojectEntry)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel6).addGap(0, 0, 0).addComponent(filler1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap())
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGap(152, 152, 152)
														.addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(layout.createSequentialGroup().addGap(180, 180, 180)
														.addComponent(jLabel6)))
												.addGap(23, 23, 23))
								.addGroup(layout.createSequentialGroup().addGap(10, 10, 10).addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(subprojectEntry)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
						.addComponent(jLabel10).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SubProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SubProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SubProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SubProjectEntry.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SubProjectEntry().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.Box.Filler filler1;
	private javax.swing.JButton buttonAddSubProjectEntry;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton populateSubProductsDropdown;
	private javax.swing.JButton buttonCancel;
	private javax.swing.JButton populateSubProductDetails;
	private javax.swing.JButton jButton22;
	private javax.swing.JButton jButton23;
	private javax.swing.JButton jButton24;
	private javax.swing.JButton jButton25;
	private javax.swing.JButton buttonReset;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private com.toedter.calendar.JCalendar jCalendar1;
	private javax.swing.JComboBox<String> dropdownCurrency;
	private javax.swing.JComboBox<String> projectNameUpdate;
	private javax.swing.JComboBox<String> projectCodeUpdate;
	private javax.swing.JComboBox<String> initialBudgetCurrency;
	private javax.swing.JComboBox<String> revisedCurrencyAmt;
	private javax.swing.JComboBox<String> subProjectIdUpdate;
	private javax.swing.JComboBox<String> subprojectNameUpdate;
	private javax.swing.JComboBox<String> jComboBox18;
	private javax.swing.JComboBox<String> jComboBox19;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JComboBox<String> jComboBox20;
	private javax.swing.JComboBox<String> jComboBox21;
	private javax.swing.JComboBox<String> jComboBox22;
	private javax.swing.JComboBox<String> jComboBox23;
	private javax.swing.JComboBox<String> dropdownProjectNameAdd;
	private javax.swing.JComboBox<String> dropdownProjectIdAdd;
	private com.toedter.calendar.JDateChooser startDateAdd;
	private com.toedter.calendar.JDateChooser initialStartDate;
	private com.toedter.calendar.JDateChooser initialEndDate;
	private com.toedter.calendar.JDateChooser revisedStartDate;
	private com.toedter.calendar.JDateChooser revisedEndDate;
	private com.toedter.calendar.JDateChooser jDateChooser15;
	private com.toedter.calendar.JDateChooser jDateChooser16;
	private com.toedter.calendar.JDateChooser jDateChooser17;
	private com.toedter.calendar.JDateChooser jDateChooser18;
	private com.toedter.calendar.JDateChooser endDateAdd;
	private com.toedter.calendar.JDateChooser revisedStartDateAdd;
	private com.toedter.calendar.JDateChooser revisedEndDateAdd;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel32;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel34;
	private javax.swing.JLabel jLabel35;
	private javax.swing.JLabel jLabel36;
	private javax.swing.JLabel jLabel37;
	private javax.swing.JLabel jLabel38;
	private javax.swing.JLabel jLabel39;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel40;
	private javax.swing.JLabel jLabel41;
	private javax.swing.JLabel jLabel42;
	private javax.swing.JLabel jLabel43;
	private javax.swing.JLabel jLabel44;
	private javax.swing.JLabel jLabel45;
	private javax.swing.JLabel jLabel46;
	private javax.swing.JLabel jLabel47;
	private javax.swing.JLabel jLabel48;
	private javax.swing.JLabel jLabel49;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel50;
	private javax.swing.JLabel jLabel51;
	private javax.swing.JLabel jLabel52;
	private javax.swing.JLabel jLabel53;
	private javax.swing.JLabel jLabel54;
	private javax.swing.JLabel jLabel55;
	private javax.swing.JLabel jLabel56;
	private javax.swing.JLabel jLabel57;
	private javax.swing.JLabel jLabel58;
	private javax.swing.JLabel jLabel59;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel addNewEntryPanel;
	private javax.swing.JPanel updateEntry;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JTabbedPane jTabbedPane5;
	private javax.swing.JTextArea textAreaDescriptionAdd;
	private javax.swing.JTextArea textAreaDescUpdate;
	private javax.swing.JTextArea jTextArea5;
	private javax.swing.JTextField subProjectCodeAdd;
	private javax.swing.JTextField percentageCompletionUpdate;
	private javax.swing.JTextField revisedContractor;
	private javax.swing.JTextField initialBudgetAmt;
	private javax.swing.JTextField revisedBudgetAmt;
	private javax.swing.JTextField jTextField16;
	private javax.swing.JTextField jTextField17;
	private javax.swing.JTextField jTextField18;
	private javax.swing.JTextField jTextField19;
	private javax.swing.JTextField budgetAmountAdd;
	private javax.swing.JTextField contractorAdd;
	private javax.swing.JTextField revisedBugetAdd;
	private javax.swing.JTextField textPercentageCompletionAdd;
	private javax.swing.JTextField subProjectNameAdd;
	private javax.swing.JTabbedPane subprojectEntry;
	// End of variables declaration//GEN-END:variables
}
