/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ourits.jobcosting.ui;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import java.util.List;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;

import com.ourits.jobcosting.entities.ProjectIdentifier;
import com.ourits.jobcosting.entities.ProjectIdentifierPK;
import com.ourits.jobcosting.entities.SubProjectIdentifier;
import com.ourits.jobcosting.entities.SubProjectIdentifierPK;
import com.ourits.jobcosting.entities.TaskDentifier;
import com.ourits.jobcosting.entities.TaskDentifierPK;
import com.ourits.jobcosting.persistencehelpers.BasePersistenceHelpers;

/**
 *
 * @author Other guest
 */
public class TaskEntry extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected TaskDentifier taskDetailsForUpdate;

	/**
	 * Creates new form NewJFrame
	 */
	public TaskEntry() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jTabbedPane5 = new javax.swing.JTabbedPane();
		jCalendar1 = new com.toedter.calendar.JCalendar();
		jLabel10 = new javax.swing.JLabel();
		filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 150),
				new java.awt.Dimension(32767, 150));
		jLabel6 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		projectEntry = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jPanel1.addPropertyChangeListener(new PropertyChangeListener() {
			public void propertyChange(PropertyChangeEvent evt) {

				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				List<ProjectIdentifier> projectIndentifiersList = basePersistenceHelpers
						.retrieveProjectIdentifiers(null);
				projectCodeAdd.removeAllItems();
				projectnameAdd.removeAllItems();
				for (ProjectIdentifier projectIdentifier : projectIndentifiersList) {
					projectCodeAdd.addItem(projectIdentifier.getId().getProjectId());
					projectnameAdd.addItem(projectIdentifier.getId().getProjectName());
				}

			}
		});
		jLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		startDateAdd = new com.toedter.calendar.JDateChooser();
		jLabel5 = new javax.swing.JLabel();
		endDateAdd = new com.toedter.calendar.JDateChooser();
		jLabel8 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jButton1 = new javax.swing.JButton();
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				performTaskAddEntry();
			}

			private void performTaskAddEntry() {
				final BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				final TaskDentifier taskIdentifier = buildTaskIdentifier();
				basePersistenceHelpers.createTaskIdentifier(taskIdentifier);
			}

			private TaskDentifier buildTaskIdentifier() {
				TaskDentifier taskDentifier = new TaskDentifier();
				TaskDentifierPK id = new TaskDentifierPK();

				id.setProjectId(projectCodeAdd.getSelectedItem().toString());
				id.setProjectName(projectnameAdd.getSelectedItem().toString());
				id.setSubProjectId(SubProjectCodeAdd.getSelectedItem().toString());
				id.setSubProjectName(subProjectNameAdd.getSelectedItem().toString());
				id.setTaskId(taskIdAdd.getText());
				id.setTaskName(taskNameAdd.getText());
				taskDentifier.setId(id);

				taskDentifier.setPercentageCompletion(new BigDecimal(percentageCompletionAdd.getText()));
				SubProjectIdentifier subProjectIdentifier = new SubProjectIdentifier();
				SubProjectIdentifierPK fkId = new SubProjectIdentifierPK();
				fkId.setProjectId(projectCodeAdd.getSelectedItem().toString());
				fkId.setProjectName(projectnameAdd.getSelectedItem().toString());
				fkId.setSubProjectId(SubProjectCodeAdd.getSelectedItem().toString());
				fkId.setSubProjectName(subProjectNameAdd.getSelectedItem().toString());

				subProjectIdentifier.setId(fkId);
				ProjectIdentifier projectIdentifier = new ProjectIdentifier();
				ProjectIdentifierPK projectId = new ProjectIdentifierPK();
				projectId.setProjectId(projectCodeAdd.getSelectedItem().toString());
				projectId.setProjectName(projectnameAdd.getSelectedItem().toString());
				projectIdentifier.setId(projectId);
				subProjectIdentifier.setProjectIdentifier(projectIdentifier);
				taskDentifier.setSubProjectIdentifier(subProjectIdentifier);
				taskDentifier.setTaskEndDate(endDateAdd.getDate());
				taskDentifier.setTaskStrtDate(startDateAdd.getDate());

				return taskDentifier;
			}

		});
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		projectnameAdd = new javax.swing.JComboBox<>();
		projectCodeAdd = new javax.swing.JComboBox<>();
		jLabel23 = new javax.swing.JLabel();
		jLabel30 = new javax.swing.JLabel();
		taskIdAdd = new javax.swing.JTextField();
		jLabel31 = new javax.swing.JLabel();
		percentageCompletionAdd = new javax.swing.JTextField();
		jLabel32 = new javax.swing.JLabel();
		jLabel33 = new javax.swing.JLabel();
		populatePossibleSubProjects = new javax.swing.JButton();
		populatePossibleSubProjects.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				projectCodeAdd.setEnabled(false);
				projectnameAdd.setEnabled(false);
				final String projectNameSelected = (String) projectnameAdd.getSelectedItem();
				final String projectCodeSelected = (String) projectCodeAdd.getSelectedItem();

				retrieveSubProjects(projectNameSelected, projectCodeSelected);
				subProjectNameAdd.setEnabled(true);
				SubProjectCodeAdd.setEnabled(true);

			}

			private void retrieveSubProjects(String projectNameSelected, String projectCodeSelected) {
				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				List<SubProjectIdentifier> subProjectIdentifiersList = basePersistenceHelpers
						.retrieveSubProjectIdentifiers(null);
				subProjectNameAdd.removeAllItems();
				SubProjectCodeAdd.removeAllItems();
				for (SubProjectIdentifier subProjectIdentifier : subProjectIdentifiersList) {
					SubProjectCodeAdd.addItem(subProjectIdentifier.getId().getSubProjectId());
					subProjectNameAdd.addItem(subProjectIdentifier.getId().getSubProjectName());
				}

			}

		});
		SubProjectCodeAdd = new javax.swing.JComboBox<>();
		subProjectNameAdd = new javax.swing.JComboBox<>();
		jLabel60 = new javax.swing.JLabel();
		taskNameAdd = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jPanel2.addPropertyChangeListener(new PropertyChangeListener() {
			public void propertyChange(PropertyChangeEvent evt) {

				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				List<ProjectIdentifier> projectIndentifiersList = basePersistenceHelpers
						.retrieveProjectIdentifiers(null);
				projectCodeUpdate.removeAllItems();
				projectNameUpdate.removeAllItems();
				for (ProjectIdentifier projectIdentifier : projectIndentifiersList) {
					projectCodeUpdate.addItem(projectIdentifier.getId().getProjectId());
					projectNameUpdate.addItem(projectIdentifier.getId().getProjectName());
				}

			}
		});
		jPanel4 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		startDateUpdate = new com.toedter.calendar.JDateChooser();
		jLabel12 = new javax.swing.JLabel();
		endDateUpdate = new com.toedter.calendar.JDateChooser();
		jLabel15 = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();
		jButton10 = new javax.swing.JButton();
		jButton10.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				taskDetailsForUpdate.setPercentageCompletion(new BigDecimal(percentageCompletionUpdate.getText()));
				taskDetailsForUpdate.setTaskStrtDate(startDateUpdate.getDate());
				taskDetailsForUpdate.setTaskEndDate(endDateUpdate.getDate());
				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				basePersistenceHelpers.updateTaskDetails(taskDetailsForUpdate);
			}
		});
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		projectNameUpdate = new javax.swing.JComboBox<>();
		projectCodeUpdate = new javax.swing.JComboBox<>();
		jLabel24 = new javax.swing.JLabel();
		jLabel61 = new javax.swing.JLabel();
		jLabel62 = new javax.swing.JLabel();
		percentageCompletionUpdate = new javax.swing.JTextField();
		jLabel63 = new javax.swing.JLabel();
		jLabel64 = new javax.swing.JLabel();
		jButton28 = new javax.swing.JButton();
		jButton28.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				projectCodeUpdate.setEnabled(false);
				projectNameUpdate.setEnabled(false);
				final String projectNameSelected = (String) projectNameUpdate.getSelectedItem();
				final String projectCodeSelected = (String) projectCodeUpdate.getSelectedItem();

				retrieveSubProjects(projectNameSelected, projectCodeSelected);
				subProjectNameUpdate.setEnabled(true);
				subProjectIdUpdate.setEnabled(true);

			}

			private void retrieveSubProjects(String projectNameSelected, String projectCodeSelected) {
				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				List<SubProjectIdentifier> subProjectIdentifiersList = basePersistenceHelpers
						.retrieveSubProjectIdentifiers(null);
				subProjectNameUpdate.removeAllItems();
				subProjectIdUpdate.removeAllItems();
				for (SubProjectIdentifier subProjectIdentifier : subProjectIdentifiersList) {
					subProjectIdUpdate.addItem(subProjectIdentifier.getId().getSubProjectId());
					subProjectNameUpdate.addItem(subProjectIdentifier.getId().getSubProjectName());
				}

			}

		});
		jButton30 = new javax.swing.JButton();
		jButton30.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				subProjectNameUpdate.setEnabled(false);
				subProjectIdUpdate.setEnabled(false);
				final String projectNameSelected = (String) projectNameUpdate.getSelectedItem();
				final String projectCodeSelected = (String) projectCodeUpdate.getSelectedItem();
				final String subprojectNameSelected = (String) subProjectNameUpdate.getSelectedItem();
				final String subprojectCodeSelected = (String) subProjectIdUpdate.getSelectedItem();

				retrieveTaskDetails(projectNameSelected, projectCodeSelected, subprojectNameSelected,
						subprojectCodeSelected);

			}

			private void retrieveTaskDetails(String projectNameSelected, String projectCodeSelected,
					String subprojectNameSelected, String subprojectCodeSelected) {
				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				List<TaskDentifier> taskIdentifiersList = basePersistenceHelpers.retrieveAllTaskDetails(null);
				taskNameUpdate.removeAllItems();
				taskcodeUpdate.removeAllItems();
				for (TaskDentifier taskDentifier : taskIdentifiersList) {
					taskcodeUpdate.addItem(taskDentifier.getId().getTaskId());
					taskNameUpdate.addItem(taskDentifier.getId().getTaskName());
				}

			}

		});
		subProjectIdUpdate = new javax.swing.JComboBox<>();
		subProjectNameUpdate = new javax.swing.JComboBox<>();
		jLabel65 = new javax.swing.JLabel();
		taskcodeUpdate = new javax.swing.JComboBox<>();
		jButton32 = new javax.swing.JButton();
		jButton32.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				subProjectNameUpdate.setEnabled(false);
				subProjectIdUpdate.setEnabled(false);
				taskNameUpdate.setEnabled(false);
				taskcodeUpdate.setEnabled(false);
				final String projectNameSelected = (String) projectNameUpdate.getSelectedItem();
				final String projectCodeSelected = (String) projectCodeUpdate.getSelectedItem();
				final String subProjectNameSelected = (String) subProjectNameUpdate.getSelectedItem();
				final String subProjectCodeSelected = (String) subProjectIdUpdate.getSelectedItem();
				final String taskCode = (String) taskcodeUpdate.getSelectedItem();
				final String taskname = (String) taskNameUpdate.getSelectedItem();

				populateTaskDetails(projectNameSelected, projectCodeSelected, subProjectNameSelected,
						subProjectCodeSelected, taskCode, taskname);

			}

			private void populateTaskDetails(String projectNameSelected, String projectCodeSelected,
					String subProjectNameSelected, String subProjectCodeSelected, String taskCode, String taskname) {
				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				TaskDentifierPK taskDentifierPK = new TaskDentifierPK();
				taskDentifierPK.setProjectId(projectCodeSelected);
				taskDentifierPK.setProjectName(projectNameSelected);
				taskDentifierPK.setSubProjectId(subProjectCodeSelected);
				taskDentifierPK.setSubProjectName(subProjectNameSelected);

				taskDentifierPK.setTaskId(taskCode);
				taskDentifierPK.setTaskName(taskname);
				taskDetailsForUpdate = basePersistenceHelpers.retrieveTaskDetails(taskDentifierPK);
				if (taskDetailsForUpdate != null) {
					projectNameUpdate.setSelectedItem(taskDetailsForUpdate.getId().getProjectName());
					projectCodeUpdate.setSelectedItem(taskDetailsForUpdate.getId().getProjectId());
					subProjectIdUpdate.setSelectedItem(taskDetailsForUpdate.getId().getSubProjectId());
					subProjectNameUpdate.setSelectedItem(taskDetailsForUpdate.getId().getSubProjectName());
					taskNameUpdate.setSelectedItem(taskDetailsForUpdate.getId().getTaskName());
					taskcodeUpdate.setSelectedItem(taskDetailsForUpdate.getId().getTaskId());

					percentageCompletionUpdate.setText(taskDetailsForUpdate.getPercentageCompletion().toString());
					startDateUpdate.setDate(taskDetailsForUpdate.getTaskStrtDate());
					endDateUpdate.setDate(taskDetailsForUpdate.getTaskEndDate());
				}

			}

		});
		taskNameUpdate = new javax.swing.JComboBox<>();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jLabel10.setText("(c) Intuitive Technologies & Solutions | All rights reserved");

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel1.setText("Task Entry Details ");

		projectEntry.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED,
				java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray,
				java.awt.Color.lightGray));

		jLabel2.setText("Project Code ");

		jLabel4.setText("Start Date");

		jLabel5.setText("End Date");

		jLabel8.setText("Project Name ");

		jButton1.setText("Add Task Entry");

		jButton2.setText("Cancel");

		jButton3.setText("Reset");

		projectnameAdd.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		projectCodeAdd.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel23.setText("Sub Project Code ");

		jLabel30.setText("Task Code");

		jLabel31.setText("% completion");

		jLabel32.setText("%");

		jLabel33.setText("Sub Project Name ");

		populatePossibleSubProjects.setText("jButton7");

		SubProjectCodeAdd.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		subProjectNameAdd.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel60.setText("Task Name");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(
										jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
												.createParallelGroup(Alignment.LEADING).addGroup(
														jPanel1Layout
																.createSequentialGroup().addGroup(jPanel1Layout
																		.createParallelGroup(Alignment.TRAILING)
																		.addComponent(jSeparator1,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addComponent(jLabel33).addGap(1)
																				.addComponent(subProjectNameAdd, 0, 247,
																						Short.MAX_VALUE)
																				.addGap(47))
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addComponent(jLabel23)
																				.addPreferredGap(
																						ComponentPlacement.RELATED)
																				.addComponent(SubProjectCodeAdd, 0, 247,
																						Short.MAX_VALUE)
																				.addGap(47))
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addGap(0, 117, Short.MAX_VALUE)
																				.addComponent(jButton1)
																				.addPreferredGap(
																						ComponentPlacement.RELATED)
																				.addComponent(jButton3).addGap(10)
																				.addComponent(jButton2).addGap(13))
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addGroup(jPanel1Layout
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addComponent(jLabel2)
																						.addComponent(jLabel4)
																						.addComponent(jLabel5)
																						.addComponent(jLabel8))
																				.addGap(11)
																				.addGroup(jPanel1Layout
																						.createParallelGroup(
																								Alignment.LEADING,
																								false)
																						.addComponent(taskNameAdd,
																								GroupLayout.PREFERRED_SIZE,
																								247,
																								GroupLayout.PREFERRED_SIZE)
																						.addGroup(jPanel1Layout
																								.createSequentialGroup()
																								.addGroup(jPanel1Layout
																										.createParallelGroup(
																												Alignment.LEADING,
																												false)
																										.addComponent(
																												startDateAdd,
																												GroupLayout.DEFAULT_SIZE,
																												263,
																												Short.MAX_VALUE)
																										.addComponent(
																												endDateAdd,
																												GroupLayout.DEFAULT_SIZE,
																												GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												projectnameAdd,
																												0,
																												GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												projectCodeAdd,
																												0,
																												GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												taskIdAdd,
																												GroupLayout.PREFERRED_SIZE,
																												247,
																												GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(
																										ComponentPlacement.UNRELATED)
																								.addComponent(
																										populatePossibleSubProjects,
																										GroupLayout.PREFERRED_SIZE,
																										35,
																										GroupLayout.PREFERRED_SIZE)))
																				.addGap(0, 0, Short.MAX_VALUE)))
																.addContainerGap())
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																.addComponent(jLabel30).addComponent(jLabel60)
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addComponent(jLabel31).addGap(14)
																		.addComponent(percentageCompletionAdd,
																				GroupLayout.PREFERRED_SIZE, 75,
																				GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(ComponentPlacement.RELATED)
																		.addComponent(jLabel32)))
														.addGap(0, 230, Short.MAX_VALUE)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup().addGap(6)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel8).addComponent(
						projectnameAdd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE))
				.addGap(18)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(projectCodeAdd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(populatePossibleSubProjects))
				.addGap(18)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel23).addComponent(
						SubProjectCodeAdd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(subProjectNameAdd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel33))
				.addGap(18)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel30).addComponent(
						taskIdAdd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel60).addComponent(
						taskNameAdd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(percentageCompletionAdd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel32).addComponent(jLabel31))
				.addGap(18)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(startDateAdd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel4))
				.addGap(18)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(endDateAdd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel5))
				.addGap(18)
				.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jButton1)
						.addComponent(jButton2).addComponent(jButton3))
				.addContainerGap()));
		jPanel1.setLayout(jPanel1Layout);

		projectEntry.addTab("New Entry", jPanel1);

		jLabel3.setText("Project Code ");

		jLabel7.setText("Start Date");

		jLabel12.setText("End Date");

		jLabel15.setText("Project Name ");

		jButton10.setText("Update Task Entry");

		jButton11.setText("Cancel");

		jButton12.setText("Reset");

		projectNameUpdate.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		projectCodeUpdate.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel24.setText("Sub Project Code ");

		jLabel61.setText("Task Code");

		jLabel62.setText("% completion");

		jLabel63.setText("%");

		jLabel64.setText("Sub Project Name ");

		jButton28.setText("jButton7");

		jButton30.setText("jButton7");

		subProjectIdUpdate.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		subProjectNameUpdate.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel65.setText("Task Name");

		taskcodeUpdate.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jButton32.setText("jButton7");

		taskNameUpdate.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		JButton btnDeleteTask = new JButton("Delete Task");
		btnDeleteTask.setAlignmentX(Component.CENTER_ALIGNMENT);
		btnDeleteTask.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				BasePersistenceHelpers basePersistenceHelpers = new BasePersistenceHelpers();
				basePersistenceHelpers.deleteTaskIdentifier(taskDetailsForUpdate);

			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4Layout
				.setHorizontalGroup(
						jPanel4Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel4Layout
								.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout.createParallelGroup(
										Alignment.LEADING)
										.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel4Layout.createSequentialGroup()
												.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
														.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
																.addComponent(jLabel24).addComponent(jLabel3)
																.addComponent(jLabel7).addComponent(jLabel12)
																.addComponent(jLabel15).addComponent(jLabel64)
																.addComponent(jLabel62).addComponent(jLabel61)
																.addComponent(jLabel65))
														.addComponent(btnDeleteTask))
												.addPreferredGap(ComponentPlacement.RELATED)
												.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
														.addGroup(jPanel4Layout.createSequentialGroup()
																.addComponent(percentageCompletionUpdate,
																		GroupLayout.PREFERRED_SIZE, 75,
																		GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(ComponentPlacement.RELATED)
																.addComponent(jLabel63))
														.addGroup(jPanel4Layout.createSequentialGroup()
																.addGroup(jPanel4Layout
																		.createParallelGroup(Alignment.LEADING)
																		.addComponent(startDateUpdate,
																				GroupLayout.DEFAULT_SIZE, 290,
																				Short.MAX_VALUE)
																		.addComponent(endDateUpdate,
																				GroupLayout.DEFAULT_SIZE, 290,
																				Short.MAX_VALUE)
																		.addGroup(jPanel4Layout.createSequentialGroup()
																				.addGroup(jPanel4Layout
																						.createParallelGroup(
																								Alignment.TRAILING)
																						.addComponent(projectCodeUpdate,
																								Alignment.LEADING, 0,
																								248, Short.MAX_VALUE)
																						.addComponent(projectNameUpdate,
																								Alignment.LEADING, 0,
																								248, Short.MAX_VALUE)
																						.addComponent(
																								subProjectIdUpdate,
																								Alignment.LEADING, 0,
																								248, Short.MAX_VALUE)
																						.addComponent(
																								subProjectNameUpdate,
																								Alignment.LEADING, 0,
																								248, Short.MAX_VALUE)
																						.addComponent(taskcodeUpdate,
																								Alignment.LEADING, 0,
																								248, Short.MAX_VALUE)
																						.addComponent(taskNameUpdate,
																								Alignment.LEADING, 0,
																								248, Short.MAX_VALUE))
																				.addPreferredGap(
																						ComponentPlacement.RELATED)
																				.addGroup(jPanel4Layout
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addComponent(jButton32,
																								GroupLayout.PREFERRED_SIZE,
																								35,
																								GroupLayout.PREFERRED_SIZE)
																						.addComponent(jButton30,
																								GroupLayout.PREFERRED_SIZE,
																								35,
																								GroupLayout.PREFERRED_SIZE)
																						.addComponent(jButton28,
																								GroupLayout.PREFERRED_SIZE,
																								35,
																								GroupLayout.PREFERRED_SIZE)))
																		.addGroup(jPanel4Layout.createSequentialGroup()
																				.addComponent(jButton10)
																				.addPreferredGap(
																						ComponentPlacement.RELATED)
																				.addComponent(jButton12).addGap(10)
																				.addComponent(jButton11)))
																.addGap(20)))))
								.addContainerGap()));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(6)
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel15)
								.addComponent(projectNameUpdate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton28))
						.addGap(18)
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel3)
								.addComponent(projectCodeUpdate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(18)
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel24)
								.addComponent(subProjectIdUpdate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton30))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel64)
								.addComponent(subProjectNameUpdate, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(15)
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel61)
								.addComponent(taskcodeUpdate, GroupLayout.PREFERRED_SIZE, 20,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton32))
						.addGap(18)
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel65)
								.addComponent(taskNameUpdate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(18).addComponent(jLabel62))
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(18)
										.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(percentageCompletionUpdate, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel63))))
						.addGap(16)
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(startDateUpdate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel7))
						.addGap(18)
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(endDateUpdate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel12))
						.addGap(18)
						.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE).addComponent(jButton10)
								.addComponent(jButton11).addComponent(jButton12).addComponent(btnDeleteTask))
						.addGap(25)));
		jPanel4.setLayout(jPanel4Layout);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 426, Short.MAX_VALUE)
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 556, Short.MAX_VALUE)
				.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))));

		projectEntry.addTab("Update Entry", jPanel2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup()
										.addComponent(projectEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 435,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel6).addGap(0, 0, 0).addComponent(filler1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap())
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(152, 152, 152).addComponent(filler1,
										javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addGap(180, 180, 180).addComponent(jLabel6)))
								.addGap(23, 23, 23))
						.addGroup(layout.createSequentialGroup().addGap(10, 10, 10).addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(projectEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 590,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addComponent(jLabel10).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TaskEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TaskEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TaskEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TaskEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TaskEntry().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.Box.Filler filler1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton populatePossibleSubProjects;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton28;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton30;
	private javax.swing.JButton jButton32;
	private com.toedter.calendar.JCalendar jCalendar1;
	private javax.swing.JComboBox<String> taskcodeUpdate;
	private javax.swing.JComboBox<String> subProjectNameAdd;
	private javax.swing.JComboBox<String> projectNameUpdate;
	private javax.swing.JComboBox<String> taskNameUpdate;
	private javax.swing.JComboBox<String> projectCodeUpdate;
	private javax.swing.JComboBox<String> subProjectIdUpdate;
	private javax.swing.JComboBox<String> subProjectNameUpdate;
	private javax.swing.JComboBox<String> projectnameAdd;
	private javax.swing.JComboBox<String> projectCodeAdd;
	private javax.swing.JComboBox<String> SubProjectCodeAdd;
	private com.toedter.calendar.JDateChooser startDateAdd;
	private com.toedter.calendar.JDateChooser endDateAdd;
	private com.toedter.calendar.JDateChooser startDateUpdate;
	private com.toedter.calendar.JDateChooser endDateUpdate;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel32;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel60;
	private javax.swing.JLabel jLabel61;
	private javax.swing.JLabel jLabel62;
	private javax.swing.JLabel jLabel63;
	private javax.swing.JLabel jLabel64;
	private javax.swing.JLabel jLabel65;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JTabbedPane jTabbedPane5;
	private javax.swing.JTextField taskIdAdd;
	private javax.swing.JTextField percentageCompletionAdd;
	private javax.swing.JTextField percentageCompletionUpdate;
	private javax.swing.JTextField taskNameAdd;
	private javax.swing.JTabbedPane projectEntry;
}
